// questionPool.js — CTI English PWA — 210+ questions statiques
// { id, category, level, type, question, options[], answer_index,
//   answer_text, hint, explication_fr, explication_en, source_cours }
'use strict';

const QUESTION_POOL = [
// ALPHABET (10)
{id:'al-01',category:'Alphabet',level:'starter',type:'qcm',question:'Comment se prononce H ?',options:['hache','éïch','ki','bi'],answer_index:1,answer_text:'éïch',hint:'Hotel.',explication_fr:"H = 'éïch'",explication_en:"H = 'aitch'",source_cours:'§29'},
{id:'al-02',category:'Alphabet',level:'starter',type:'qcm',question:'Comment se prononce G ?',options:['gé','dji','gi','je'],answer_index:1,answer_text:'dji',hint:'Djinn.',explication_fr:"G = 'dji'",explication_en:"G = 'jee'",source_cours:'§29'},
{id:'al-03',category:'Alphabet',level:'starter',type:'qcm',question:'Comment se prononce W ?',options:['vi','double v','dabel you','oué'],answer_index:2,answer_text:'dabel you',hint:'Double U.',explication_fr:"W = 'dabel you'",explication_en:"W = 'double-you'",source_cours:'§29'},
{id:'al-04',category:'Alphabet',level:'starter',type:'qcm',question:"Combien de lettres dans l'alphabet anglais ?",options:['24','25','26','28'],answer_index:2,answer_text:'26',hint:'A→Z.',explication_fr:'26 lettres.',explication_en:'26 letters.',source_cours:'§29'},
{id:'al-05',category:'Alphabet',level:'starter',type:'qcm',question:'Comment se prononce Y ?',options:['yi','oui','waï','yé'],answer_index:2,answer_text:'waï',hint:'Rime avec why.',explication_fr:"Y = 'waï'",explication_en:"Y = 'why'",source_cours:'§29'},
{id:'al-06',category:'Alphabet',level:'starter',type:'qcm',question:'Quelle lettre se prononce "zed" (UK) ou "zee" (US) ?',options:['S','X','Z','C'],answer_index:2,answer_text:'Z',hint:'Dernière lettre.',explication_fr:'Z = zed/zee.',explication_en:'Z = last letter.',source_cours:'§29'},
{id:'al-07',category:'Alphabet',level:'starter',type:'qcm',question:'"How do you spell your name?" signifie :',options:['Qui êtes-vous ?','Quel surnom ?','Comment épelez-vous votre nom ?','Quel prénom ?'],answer_index:2,answer_text:'Comment épelez-vous',hint:"Spell = épeler.",explication_fr:"Spell = épeler lettre à lettre.",explication_en:"How do you spell? = say the letters.",source_cours:'§29'},
{id:'al-08',category:'Alphabet',level:'builder',type:'qcm',question:'"Surname" signifie :',options:['Prénom','2ème prénom','Nom de famille','Surnom'],answer_index:2,answer_text:'Nom de famille',hint:'= Family name.',explication_fr:"Surname = nom de famille.",explication_en:"Surname = family name.",source_cours:'§29'},
{id:'al-09',category:'Alphabet',level:'starter',type:'qcm',question:'Comment se prononce Q ?',options:['ki','kiou','ku','qu'],answer_index:1,answer_text:'kiou',hint:'Rime avec blue.',explication_fr:"Q = 'kiou'",explication_en:"Q = 'cue'",source_cours:'§29'},
{id:'al-10',category:'Alphabet',level:'builder',type:'qcm',question:'Laquelle se prononce "éï" ?',options:['E','A','I','O'],answer_index:1,answer_text:'A',hint:'Pense à April.',explication_fr:"A = 'éï'",explication_en:"A = 'ay'",source_cours:'§29'},

// TO BE PRÉSENT (12)
{id:'tbp-01',category:'To Be',level:'starter',type:'qcm',question:'Forme correcte pour "She" au présent :',options:['She are','She am','She is','She be'],answer_index:2,answer_text:'She is',hint:'He/She/It →?',explication_fr:'He/She/It → IS.',explication_en:'She IS.',source_cours:'§27'},
{id:'tbp-02',category:'To Be',level:'starter',type:'qcm',question:'"We ___ tired." :',options:['am','is','are','be'],answer_index:2,answer_text:'are',hint:'We = pluriel.',explication_fr:'We → ARE.',explication_en:'We ARE.',source_cours:'§27'},
{id:'tbp-03',category:'To Be',level:'starter',type:'qcm',question:'Forme négative de "I am" :',options:["I'm not","I amn't","I not am","I be not"],answer_index:0,answer_text:"I'm not",hint:"Contraction correcte.",explication_fr:"I AM NOT → I'M NOT.",explication_en:"I'm not (only correct contraction).",source_cours:'§27'},
{id:'tbp-04',category:'To Be',level:'starter',type:'lacune',question:'___ you busy now?',answer_text:'Are',hint:'Forme interrog. / You.',explication_fr:'ARE + you = question.',explication_en:'Are you...?',source_cours:'§27'},
{id:'tbp-05',category:'To Be',level:'starter',type:'qcm',question:'"I\'m off" signifie :',options:['En retard','Fatigué','Je m\'en vais','Je suis libre'],answer_index:2,answer_text:"Je m'en vais",hint:"Off = partir.",explication_fr:"I'm off = je pars.",explication_en:"I'm off = I'm leaving.",source_cours:'§28'},
{id:'tbp-06',category:'To Be',level:'builder',type:'qcm',question:'Forme interro-négative de "You are" :',options:['Are you not?','You are not?','Is you not?','Not are you?'],answer_index:0,answer_text:'Are you not?',hint:'Inversion sujet-verbe.',explication_fr:'ARE + YOU + NOT?',explication_en:"Aren't you? / Are you not?",source_cours:'§27'},
{id:'tbp-07',category:'To Be',level:'builder',type:'qcm',question:'"To be in a rush" signifie :',options:['être relaxé','être en retard','être pressé','être libre'],answer_index:2,answer_text:'être pressé',hint:"Rush = précipitation.",explication_fr:"In a rush = pressé.",explication_en:"In a rush = in a hurry.",source_cours:'§24'},
{id:'tbp-08',category:'To Be',level:'builder',type:'lacune',question:'She ___ not happy.',answer_text:'is',hint:'She → 3ème pers. sing.',explication_fr:'She IS NOT.',explication_en:"She isn't happy.",source_cours:'§27'},
{id:'tbp-09',category:'To Be',level:'starter',type:'qcm',question:'"To be late" signifie :',options:['fatigué','en retard','occupé','en avance'],answer_index:1,answer_text:'en retard',hint:'Late ≠ early.',explication_fr:"Late = en retard.",explication_en:"Late = not on time.",source_cours:'§27'},
{id:'tbp-10',category:'To Be',level:'builder',type:'qcm',question:'Phrase correcte :',options:['He are a student.','She am tired.','They is late.','I am ready.'],answer_index:3,answer_text:'I am ready.',hint:'Accord sujet-verbe.',explication_fr:'I AM est la seule phrase correcte.',explication_en:'I AM is correct.',source_cours:'§27'},
{id:'tbp-11',category:'To Be',level:'starter',type:'qcm',question:'"To be busy" signifie :',options:['libre','fatigué','occupé','pressé'],answer_index:2,answer_text:'occupé',hint:'Busy = occupé.',explication_fr:"Busy = occupé.",explication_en:"I'm busy = I have things to do.",source_cours:'§27'},
{id:'tbp-12',category:'To Be',level:'challenger',type:'traduction',question:'Traduire : "Ils ne sont pas disponibles le vendredi."',answer_text:'They are not available on Fridays.',hint:"'On' + jours.",explication_fr:'They ARE NOT. On Fridays = habitude.',explication_en:'They are not available on Fridays.',source_cours:'§27'},

// TO BE PASSÉ (10)
{id:'tbpa-01',category:'To Be (Passé)',level:'starter',type:'qcm',question:'Passé de "I am" :',options:['I were','I was','I beed','I had'],answer_index:1,answer_text:'I was',hint:'I/He/She/It → ?',explication_fr:'I → WAS au passé.',explication_en:'I WAS.',source_cours:'§15'},
{id:'tbpa-02',category:'To Be (Passé)',level:'starter',type:'qcm',question:'"They ___ at school yesterday." :',options:['was','were','are','be'],answer_index:1,answer_text:'were',hint:'They → pluriel passé.',explication_fr:'They → WERE.',explication_en:'They WERE.',source_cours:'§15'},
{id:'tbpa-03',category:'To Be (Passé)',level:'starter',type:'lacune',question:'___ you at home last night?',answer_text:'Were',hint:'Question passé / You.',explication_fr:'WERE + you? = interrogatif passé.',explication_en:'Were you...? = past question.',source_cours:'§15'},
{id:'tbpa-04',category:'To Be (Passé)',level:'builder',type:'qcm',question:'"She was not here" est :',options:['présent négatif','passé négatif','futur','présent interrog.'],answer_index:1,answer_text:'passé négatif',hint:"'Was' = passé.",explication_fr:'WAS NOT = passé négatif.',explication_en:'WAS NOT = past negative.',source_cours:'§15'},
{id:'tbpa-05',category:'To Be (Passé)',level:'builder',type:'qcm',question:'"To be lost" signifie :',options:['fatigué','perdu','coincé','privé de'],answer_index:1,answer_text:'perdu',hint:"Diallo à Saint-Louis.",explication_fr:"Lost = perdu.",explication_en:"I was lost = I didn't know where I was.",source_cours:'§16'},
{id:'tbpa-06',category:'To Be (Passé)',level:'builder',type:'qcm',question:'"Traffic jam" signifie :',options:['feu rouge','embouteillage','accident','autoroute'],answer_index:1,answer_text:'embouteillage',hint:'Très courant à Dakar.',explication_fr:"Traffic jam = embouteillage.",explication_en:"Traffic jam = blocked road.",source_cours:'§16'},
{id:'tbpa-07',category:'To Be (Passé)',level:'starter',type:'qcm',question:'"He ___ not at the market." :',options:['were','was','is','are'],answer_index:1,answer_text:'was',hint:'He = singulier.',explication_fr:'He → WAS.',explication_en:'He WAS NOT.',source_cours:'§15'},
{id:'tbpa-08',category:'To Be (Passé)',level:'builder',type:'qcm',question:'"To be stuck" signifie :',options:['libre','en retard','coincé','pressé'],answer_index:2,answer_text:'coincé',hint:'Embouteillage Dakar.',explication_fr:"Stuck = coincé, bloqué.",explication_en:"Stuck = unable to move.",source_cours:'§16'},
{id:'tbpa-09',category:'To Be (Passé)',level:'challenger',type:'traduction',question:'Traduire : "Pourquoi étais-tu si pressé hier ?"',answer_text:'Why were you in such a rush yesterday?',hint:"Such a rush.",explication_fr:'WHY + WERE + YOU + passé.',explication_en:'Why were you in such a rush?',source_cours:'§15'},
{id:'tbpa-10',category:'To Be (Passé)',level:'builder',type:'qcm',question:'"By the way" signifie :',options:['de toute façon','au fait','tout de suite','de ce côté'],answer_index:1,answer_text:'au fait',hint:"Intro à une nouvelle info.",explication_fr:"By the way = au fait.",explication_en:"By the way = incidentally.",source_cours:'§16'},

// TO HAVE PRÉSENT (12)
{id:'thp-01',category:'To Have',level:'starter',type:'qcm',question:'Forme correcte pour "She" :',options:['She have','She had','She has','She haves'],answer_index:2,answer_text:'She has',hint:'He/She/It → ?',explication_fr:'She → HAS.',explication_en:'She HAS.',source_cours:'§22'},
{id:'thp-02',category:'To Have',level:'starter',type:'qcm',question:'"To have an impediment" signifie :',options:['une idée','pitié','un empêchement','des mots'],answer_index:2,answer_text:'un empêchement',hint:'Diallo le dit à Emma.',explication_fr:"Impediment = empêchement.",explication_en:"An impediment = something blocking you.",source_cours:'§23'},
{id:'thp-03',category:'To Have',level:'starter',type:'lacune',question:'___ she got an idea?',answer_text:'Has',hint:'Has/Have got = To Have.',explication_fr:'HAS she got? = Does she have?',explication_en:'Has she got? = Does she have?',source_cours:'§22'},
{id:'thp-04',category:'To Have',level:'starter',type:'qcm',question:'"DON\'T" = :',options:["Doesn't","Do not","Didn't","Won't"],answer_index:1,answer_text:'Do not',hint:'Contraction simple.',explication_fr:"DON'T = DO NOT.",explication_en:"DON'T = DO NOT.",source_cours:'§22'},
{id:'thp-05',category:'To Have',level:'builder',type:'qcm',question:'"To have mercy" signifie :',options:['des mots','pitié','des connaissances','des manières'],answer_index:1,answer_text:'pitié',hint:"Mercy = clémence.",explication_fr:"Mercy = pitié, clémence.",explication_en:"Have mercy = be compassionate.",source_cours:'§17'},
{id:'thp-06',category:'To Have',level:'builder',type:'qcm',question:'Phrase correcte :',options:['Do she have time?','Does she have time?','Has she time done?','Is she have time?'],answer_index:1,answer_text:'Does she have time?',hint:'She → DOES.',explication_fr:'DOES + she + have (base).',explication_en:'Does she have time?',source_cours:'§22'},
{id:'thp-07',category:'To Have',level:'builder',type:'lacune',question:'I do not ___ a car.',answer_text:'have',hint:'DO NOT → base verbale.',explication_fr:"DO NOT + base verbale.",explication_en:"I do not HAVE.",source_cours:'§22'},
{id:'thp-08',category:'To Have',level:'builder',type:'qcm',question:'"To have manners" signifie :',options:['des mots','de la chance','des manières','des nouvelles'],answer_index:2,answer_text:'des manières',hint:"Manners = politesse.",explication_fr:"Manners = bonnes manières.",explication_en:"Have manners = be polite.",source_cours:'§17'},
{id:'thp-09',category:'To Have',level:'builder',type:'qcm',question:'"DOESN\'T" = :',options:["Did not","Do not","Does not","Has not"],answer_index:2,answer_text:'Does not',hint:"3ème pers. sing.",explication_fr:"DOESN'T = DOES NOT.",explication_en:"DOESN'T = DOES NOT.",source_cours:'§22'},
{id:'thp-10',category:'To Have',level:'builder',type:'qcm',question:'"To have nausea" signifie :',options:['faim','la nausée','froid','de la fièvre'],answer_index:1,answer_text:'la nausée',hint:"Nausea = envie de vomir.",explication_fr:"Nausea = la nausée.",explication_en:"To have nausea = to feel sick.",source_cours:'§22'},
{id:'thp-11',category:'To Have',level:'challenger',type:'traduction',question:'Traduire : "Est-ce qu\'elle a des nouvelles de Diallo ?"',answer_text:"Does she have any news from Diallo?",hint:"'Any' en question.",explication_fr:"DOES + she + have + any news.",explication_en:"Does she have any news?",source_cours:'§22'},
{id:'thp-12',category:'To Have',level:'starter',type:'qcm',question:'"To have an appetite" signifie :',options:['un empêchement','de l\'appétit','une idée','de la chance'],answer_index:1,answer_text:"de l'appétit",hint:"Appetite = faim.",explication_fr:"Appetite = appétit.",explication_en:"To have an appetite = to feel hungry.",source_cours:'§22'},

// TO HAVE PASSÉ (10)
{id:'thpa-01',category:'To Have (Passé)',level:'starter',type:'qcm',question:'Passé de "to have" pour tous :',options:['has','have','had','haved'],answer_index:2,answer_text:'had',hint:'Une seule forme.',explication_fr:'Tous → HAD.',explication_en:'ALL subjects → HAD.',source_cours:'§9'},
{id:'thpa-02',category:'To Have (Passé)',level:'starter',type:'qcm',question:'"HAD NOT" → contraction :',options:["Didn't","Wouldn't","Hadn't","Hasn't"],answer_index:2,answer_text:"Hadn't",hint:'HAD + NOT.',explication_fr:"HAD NOT → HADN'T.",explication_en:"HADN'T = HAD NOT.",source_cours:'§9'},
{id:'thpa-03',category:'To Have (Passé)',level:'builder',type:'qcm',question:'2ème forme négative passé de "to have" :',options:["Hadn't","Didn't have","Hasn't","Doesn't have"],answer_index:1,answer_text:"Didn't have",hint:'2 formes négatives.',explication_fr:"HADN'T + DID NOT HAVE.",explication_en:"Two forms: HADN'T or DIDN'T HAVE.",source_cours:'§9'},
{id:'thpa-04',category:'To Have (Passé)',level:'starter',type:'lacune',question:'She ___ no luck yesterday.',answer_text:'had',hint:'Passé → une forme.',explication_fr:"She HAD no luck.",explication_en:"She HAD no luck yesterday.",source_cours:'§10'},
{id:'thpa-05',category:'To Have (Passé)',level:'builder',type:'qcm',question:'"To have a bone to pick" signifie :',options:['avoir faim','avoir un os','un compte à régler','mal aux dents'],answer_index:2,answer_text:'un compte à régler',hint:"Expression idiomatique.",explication_fr:"Avoir un compte à régler.",explication_en:"A grievance to discuss.",source_cours:'§9'},
{id:'thpa-06',category:'To Have (Passé)',level:'builder',type:'qcm',question:'"Unexpected" signifie :',options:['attendu','prévisible','inattendu','important'],answer_index:2,answer_text:'inattendu',hint:"Un- = négatif.",explication_fr:"Unexpected = inattendu.",explication_en:"Unexpected = surprising.",source_cours:'§10'},
{id:'thpa-07',category:'To Have (Passé)',level:'builder',type:'lacune',question:'___ they have fun at the party?',answer_text:'Did',hint:'DID = auxiliaire passé.',explication_fr:'DID + they + have (base).',explication_en:'DID they have fun?',source_cours:'§9'},
{id:'thpa-08',category:'To Have (Passé)',level:'challenger',type:'traduction',question:'Traduire : "Elle n\'avait pas accès à Internet hier."',answer_text:"She didn't have access to the internet yesterday.",hint:"Access TO + chose.",explication_fr:"DIDN'T HAVE access to...",explication_en:"She didn't have access to the internet.",source_cours:'§9'},
{id:'thpa-09',category:'To Have (Passé)',level:'builder',type:'qcm',question:'"To have a feeling" signifie :',options:['de la fièvre','une impression','pitié','du sentiment'],answer_index:1,answer_text:'une impression',hint:"A feeling = pressentiment.",explication_fr:"I have a feeling = j'ai l'impression.",explication_en:"I have a feeling = I sense.",source_cours:'§9'},
{id:'thpa-10',category:'To Have (Passé)',level:'builder',type:'qcm',question:'"To have fun" signifie :',options:['être drôle','s\'amuser','avoir de la chance','rire de'],answer_index:1,answer_text:"s'amuser",hint:"Fun = plaisir.",explication_fr:"Have fun = s'amuser.",explication_en:"Have fun = enjoy yourself.",source_cours:'§9'},

// PRESENT PERFECT (10)
{id:'pp-01',category:'Present Perfect',level:'builder',type:'qcm',question:'Le Present Perfect = :',options:['To Be + base','Have/Has + PP','Did + base','Will + inf'],answer_index:1,answer_text:'Have/Has + PP',hint:'Have/Has + PP.',explication_fr:'HAVE/HAS + Past Participle.',explication_en:'HAVE/HAS + Past Participle.',source_cours:'§6'},
{id:'pp-02',category:'Present Perfect',level:'builder',type:'qcm',question:'"bought" dans "She has bought" est :',options:['passé simple','participe passé','infinitif','gérondif'],answer_index:1,answer_text:'participe passé',hint:'Buy → bought → bought.',explication_fr:"Bought = PP de buy.",explication_en:"Bought = past participle of buy.",source_cours:'§6'},
{id:'pp-03',category:'Present Perfect',level:'builder',type:'lacune',question:'I have ___ arrived. (venir de)',answer_text:'just',hint:'Have + JUST + PP.',explication_fr:"JUST → venir de faire.",explication_en:"Have just + PP = recently done.",source_cours:'§6'},
{id:'pp-04',category:'Present Perfect',level:'builder',type:'qcm',question:'Négative de "She has worked" :',options:["She hasn't worked","She didn't worked","She not has worked","She haven't worked"],answer_index:0,answer_text:"She hasn't worked",hint:"Has + NOT = ?",explication_fr:"HASN'T worked.",explication_en:"She HASN'T worked.",source_cours:'§6'},
{id:'pp-05',category:'Present Perfect',level:'builder',type:'qcm',question:'Interrogative de "He has seen the film" :',options:['Did he see?','Has he seen?','Have he seen?','He has seen?'],answer_index:1,answer_text:'Has he seen?',hint:'Inverser HAS + sujet.',explication_fr:'HAS + he + PP?',explication_en:'HAS he seen?',source_cours:'§6'},
{id:'pp-06',category:'Present Perfect',level:'builder',type:'qcm',question:'"To book" signifie :',options:['lire','réserver','payer','annuler'],answer_index:1,answer_text:'réserver',hint:"Emma a booké son billet.",explication_fr:"Book = réserver.",explication_en:"To book = to reserve.",source_cours:'§3'},
{id:'pp-07',category:'Present Perfect',level:'challenger',type:'traduction',question:'Traduire : "Diallo vient juste de finir son travail."',answer_text:'Diallo has just finished his work.',hint:'Has + JUST + PP.',explication_fr:'HAS JUST + finished.',explication_en:'Has just finished.',source_cours:'§6'},
{id:'pp-08',category:'Present Perfect',level:'challenger',type:'qcm',question:'Phrase correcte :',options:['She have eat lunch.','She has eaten lunch.','She is eaten lunch.','She had eat lunch.'],answer_index:1,answer_text:'She has eaten lunch.',hint:'Has + PP irrégulier.',explication_fr:"She HAS EATEN. Eat → eaten.",explication_en:"She has EATEN.",source_cours:'§6'},
{id:'pp-09',category:'Present Perfect',level:'builder',type:'lacune',question:'Have they ___ (buy) the tickets?',answer_text:'bought',hint:'Buy → PP irrégulier.',explication_fr:"Buy → BOUGHT (PP).",explication_en:"BUY → BOUGHT.",source_cours:'§6'},
{id:'pp-10',category:'Present Perfect',level:'builder',type:'qcm',question:'"To keep in touch" signifie :',options:['se perdre de vue','garder contact','se retrouver','se souvenir'],answer_index:1,answer_text:'garder contact',hint:"Emma dit ça à Faby.",explication_fr:"Keep in touch = garder contact.",explication_en:"Keep in touch = stay connected.",source_cours:'§3'},

// PAST SIMPLE (15)
{id:'ps-01',category:'Past Simple',level:'starter',type:'qcm',question:'Passé de "go" :',options:['goed','gone','went','go'],answer_index:2,answer_text:'went',hint:'Irrégulier.',explication_fr:"Go → WENT.",explication_en:"Go → WENT.",source_cours:'§30'},
{id:'ps-02',category:'Past Simple',level:'starter',type:'qcm',question:'Passé de "see" :',options:['seed','sawed','seen','saw'],answer_index:3,answer_text:'saw',hint:'See/saw/seen.',explication_fr:"See → SAW.",explication_en:"See → SAW.",source_cours:'§30'},
{id:'ps-03',category:'Past Simple',level:'starter',type:'qcm',question:'Passé de "buy" :',options:['buyed','buied','bought','boughted'],answer_index:2,answer_text:'bought',hint:'Buy/bought/bought.',explication_fr:"Buy → BOUGHT.",explication_en:"Buy → BOUGHT.",source_cours:'§30'},
{id:'ps-04',category:'Past Simple',level:'starter',type:'qcm',question:'Forme négative passé correcte :',options:["I didn't went","I not went","I didn't go","I don't went"],answer_index:2,answer_text:"I didn't go",hint:"DID NOT + base.",explication_fr:"DIDN'T + GO (base).",explication_en:"DIDN'T GO.",source_cours:'§2'},
{id:'ps-05',category:'Past Simple',level:'builder',type:'qcm',question:'Question correcte au passé :',options:['Did he went?','Did he go?','He went?','Does he went?'],answer_index:1,answer_text:'Did he go?',hint:'DID + base verbale.',explication_fr:'DID + sujet + base.',explication_en:'Did he GO?',source_cours:'§2'},
{id:'ps-06',category:'Past Simple',level:'starter',type:'lacune',question:'She ___ (visit) Paris last year.',answer_text:'visited',hint:'Régulier → +ED.',explication_fr:"Visit → VISITED.",explication_en:"VISIT + ED = VISITED.",source_cours:'§2'},
{id:'ps-07',category:'Past Simple',level:'builder',type:'lacune',question:'I ___ (write) a letter yesterday.',answer_text:'wrote',hint:'Irrégulier.',explication_fr:"Write → WROTE.",explication_en:"Write → WROTE.",source_cours:'§30'},
{id:'ps-08',category:'Past Simple',level:'builder',type:'qcm',question:'Passé de "eat" :',options:['eated','ated','eaten','ate'],answer_index:3,answer_text:'ate',hint:'Eat/ate/eaten.',explication_fr:"Eat → ATE.",explication_en:"Eat → ATE.",source_cours:'§30'},
{id:'ps-09',category:'Past Simple',level:'starter',type:'qcm',question:'Passé de "take" :',options:['taked','took','token','take'],answer_index:1,answer_text:'took',hint:'Take/took/taken.',explication_fr:"Take → TOOK.",explication_en:"Take → TOOK.",source_cours:'§30'},
{id:'ps-10',category:'Past Simple',level:'builder',type:'qcm',question:'Passé de "know" :',options:['knowed','known','knew','knewed'],answer_index:2,answer_text:'knew',hint:'Know/knew/known.',explication_fr:"Know → KNEW.",explication_en:"Know → KNEW.",source_cours:'§30'},
{id:'ps-11',category:'Past Simple',level:'builder',type:'qcm',question:'Passé de "find" :',options:['finded','founded','found','find'],answer_index:2,answer_text:'found',hint:'Find/found/found.',explication_fr:"Find → FOUND.",explication_en:"Find → FOUND.",source_cours:'§30'},
{id:'ps-12',category:'Past Simple',level:'builder',type:'qcm',question:'Passé de "come" :',options:['comed','came','come','comes'],answer_index:1,answer_text:'came',hint:'Come/came/come.',explication_fr:"Come → CAME.",explication_en:"Come → CAME.",source_cours:'§30'},
{id:'ps-13',category:'Past Simple',level:'challenger',type:'traduction',question:'Traduire : "Elle n\'a pas voulu aller à la fête hier soir."',answer_text:"She didn't want to go to the party last night.",hint:"Didn't + base.",explication_fr:"DIDN'T + WANT + TO GO.",explication_en:"She didn't want to go.",source_cours:'§2'},
{id:'ps-14',category:'Past Simple',level:'builder',type:'qcm',question:'Passé de "give" :',options:['gived','gave','given','give'],answer_index:1,answer_text:'gave',hint:'Give/gave/given.',explication_fr:"Give → GAVE.",explication_en:"Give → GAVE.",source_cours:'§30'},
{id:'ps-15',category:'Past Simple',level:'starter',type:'qcm',question:'"I worked" est au passé :',options:['irrégulier','régulier','futur','continu'],answer_index:1,answer_text:'régulier',hint:"Work + ed.",explication_fr:"Worked = régulier + ED.",explication_en:"Worked = regular past.",source_cours:'§2'},

// WH QUESTIONS (15)
{id:'wh-01',category:'WH Questions',level:'starter',type:'qcm',question:'WH question pour "pourquoi" ?',options:['When','Where','Why','Which'],answer_index:2,answer_text:'Why',hint:'W-H-Y.',explication_fr:"WHY = pourquoi.",explication_en:"WHY = pourquoi.",source_cours:'§11'},
{id:'wh-02',category:'WH Questions',level:'starter',type:'qcm',question:'WH question pour une personne (sujet) ?',options:['Whom','Whose','Which','Who'],answer_index:3,answer_text:'Who',hint:'WHO sujet.',explication_fr:"WHO = qui (sujet).",explication_en:"WHO = subject person.",source_cours:'§11'},
{id:'wh-03',category:'WH Questions',level:'builder',type:'qcm',question:'"Whose book is this?" = :',options:['Où est ce livre ?','À qui appartient ce livre ?','Quel livre ?','Pourquoi ce livre ?'],answer_index:1,answer_text:'À qui appartient ce livre ?',hint:'Whose = possession.',explication_fr:"WHOSE = à qui.",explication_en:"Whose = possession.",source_cours:'§11'},
{id:'wh-04',category:'WH Questions',level:'starter',type:'qcm',question:'"When were you born?" = :',options:['Où es-tu né ?','Qui es-tu ?','Quand es-tu né ?','Pourquoi ?'],answer_index:2,answer_text:'Quand es-tu né ?',hint:'WHEN = temps.',explication_fr:"WHEN = quand.",explication_en:"WHEN = about time.",source_cours:'§11'},
{id:'wh-05',category:'WH Questions',level:'builder',type:'qcm',question:'"How far is it?" = :',options:["C'est comment ?","C'est loin ?","C'est combien ?","Depuis quand ?"],answer_index:1,answer_text:"C'est loin ?",hint:'HOW FAR = distance.',explication_fr:"How far = à quelle distance.",explication_en:"How far = distance.",source_cours:'§11'},
{id:'wh-06',category:'WH Questions',level:'builder',type:'qcm',question:'"It\'s crowded!" = :',options:["C'est silencieux !","C'est bondé !","C'est propre !","C'est loin !"],answer_index:1,answer_text:"C'est bondé !",hint:'Crowded = plein de monde.',explication_fr:"Crowded = bondé.",explication_en:"Crowded = full of people.",source_cours:'§12'},
{id:'wh-07',category:'WH Questions',level:'builder',type:'qcm',question:'"Gimme 5 min." = :',options:['Give to me (5 min)','Give me (familier)','Gave me','Have me'],answer_index:1,answer_text:'Give me',hint:"Gimme = Give me.",explication_fr:"Gimme = Give me (argot).",explication_en:"Gimme = Give me (informal).",source_cours:'§12'},
{id:'wh-08',category:'WH Questions',level:'starter',type:'lacune',question:'___ are you with? (Qui es-tu avec ?)',answer_text:'Who',hint:'WHO = personne.',explication_fr:"WHO = qui.",explication_en:"Who asks about people.",source_cours:'§11'},
{id:'wh-09',category:'WH Questions',level:'builder',type:'qcm',question:'"Restroom" (US) = :',options:['Chambre','Salle de repos','Toilettes','Cuisine'],answer_index:2,answer_text:'Toilettes',hint:'Terme américain.',explication_fr:"Restroom (US) = toilettes.",explication_en:"Restroom = toilet.",source_cours:'§12'},
{id:'wh-10',category:'WH Questions',level:'builder',type:'qcm',question:'"Which" s\'utilise quand :',options:['la réponse est inconnue','le choix est limité','la question est formelle','le sujet est personne'],answer_index:1,answer_text:'le choix est limité',hint:'Which = ensemble défini.',explication_fr:"WHICH = choix limité.",explication_en:"WHICH = limited choices.",source_cours:'§11'},
{id:'wh-11',category:'WH Questions',level:'challenger',type:'traduction',question:'Traduire : "Lequel de ces exercices préfères-tu ?"',answer_text:'Which of these exercises do you prefer?',hint:'Which = choix limité.',explication_fr:'WHICH of these... do you prefer?',explication_en:'Which of these exercises do you prefer?',source_cours:'§11'},
{id:'wh-12',category:'WH Questions',level:'builder',type:'qcm',question:'"How long does it take?" = :',options:["Comment y arriver ?","Combien de temps ?","Depuis quand ?","C'est loin ?"],answer_index:1,answer_text:'Combien de temps ?',hint:'How LONG = durée.',explication_fr:"How long = durée.",explication_en:"How long = duration.",source_cours:'§11'},
{id:'wh-13',category:'WH Questions',level:'starter',type:'qcm',question:'"Where" s\'utilise pour :',options:['le temps','la manière','le lieu','la raison'],answer_index:2,answer_text:'le lieu',hint:'WHERE = endroit.',explication_fr:"WHERE = lieu.",explication_en:"WHERE = place.",source_cours:'§11'},
{id:'wh-14',category:'WH Questions',level:'builder',type:'qcm',question:'"What\'s happening?" = :',options:["Qu'est-il arrivé ?","Qu'est-ce qui se passe ?","Qui est là ?","Quand ?"],answer_index:1,answer_text:"Qu'est-ce qui se passe ?",hint:"Present continuous.",explication_fr:"What's happening? = Qu'est-ce qui se passe?",explication_en:"What's happening? = What is going on?",source_cours:'§12'},
{id:'wh-15',category:'WH Questions',level:'builder',type:'lacune',question:'___ is it? (Où est-ce ?)',answer_text:'Where',hint:'WHERE = lieu.',explication_fr:"WHERE = où.",explication_en:"Where = location.",source_cours:'§11'},

// BEAUCOUP (10)
{id:'bcp-01',category:'Beaucoup',level:'starter',type:'qcm',question:'"Much" s\'utilise avec :',options:['dénombrables pluriels','indénombrables','noms propres','verbes'],answer_index:1,answer_text:'indénombrables',hint:'Cannot count → much.',explication_fr:"MUCH + indénombrable.",explication_en:"MUCH + uncountable.",source_cours:'§13'},
{id:'bcp-02',category:'Beaucoup',level:'starter',type:'qcm',question:'"Many" s\'utilise avec :',options:['indénombrables','dénombrables pluriels','singuliers','adjectifs'],answer_index:1,answer_text:'dénombrables pluriels',hint:'Can count → many.',explication_fr:"MANY + dénombrable pluriel.",explication_en:"MANY + countable plural.",source_cours:'§13'},
{id:'bcp-03',category:'Beaucoup',level:'starter',type:'qcm',question:'Phrase correcte :',options:['She speaks much languages.','She speaks many languages.','She speaks several language.','She speaks lots language.'],answer_index:1,answer_text:'She speaks many languages.',hint:"Languages = pluriel.",explication_fr:"MANY languages (dénombrable).",explication_en:"MANY languages.",source_cours:'§13'},
{id:'bcp-04',category:'Beaucoup',level:'builder',type:'qcm',question:'"A lot of" fonctionne avec :',options:['dénombrables seul','indénombrables seul','les deux','verbes seul'],answer_index:2,answer_text:'les deux',hint:"Le plus polyvalent.",explication_fr:"A LOT OF = les deux.",explication_en:"A LOT OF = both types.",source_cours:'§13'},
{id:'bcp-05',category:'Beaucoup',level:'starter',type:'qcm',question:'"Fortnight" = :',options:['une semaine','quinze jours','un mois','deux heures'],answer_index:1,answer_text:'quinze jours',hint:'Fourteen nights.',explication_fr:"Fortnight = quinze jours.",explication_en:"Fortnight = two weeks.",source_cours:'§13'},
{id:'bcp-06',category:'Beaucoup',level:'builder',type:'qcm',question:'"Several" = :',options:['beaucoup','aucun','plusieurs','un peu de'],answer_index:2,answer_text:'plusieurs',hint:'More than two.',explication_fr:"Several = plusieurs.",explication_en:"Several = more than two.",source_cours:'§13'},
{id:'bcp-07',category:'Beaucoup',level:'builder',type:'qcm',question:'"Plenty of" = :',options:['pas assez','amplement','peu','autant'],answer_index:1,answer_text:'amplement',hint:"En abondance.",explication_fr:"Plenty of = amplement.",explication_en:"Plenty of = more than enough.",source_cours:'§13'},
{id:'bcp-08',category:'Beaucoup',level:'builder',type:'lacune',question:'I can\'t eat ___ rice.',answer_text:'much',hint:"Rice = indénombrable.",explication_fr:"MUCH + rice.",explication_en:"MUCH rice (uncountable).",source_cours:'§13'},
{id:'bcp-09',category:'Beaucoup',level:'challenger',type:'traduction',question:'Traduire : "Il y a beaucoup de monde dans ce car rapide."',answer_text:'There are a lot of people in this car rapide.',hint:"People = dénombrable.",explication_fr:"A lot of people.",explication_en:"There are a lot of people.",source_cours:'§13'},
{id:'bcp-10',category:'Beaucoup',level:'builder',type:'qcm',question:'"Lots of" = :',options:['Much','A lot of','Many only','Few'],answer_index:1,answer_text:'A lot of',hint:"Lots = a lot (informel).",explication_fr:"Lots of = a lot of.",explication_en:"Lots of = a lot of.",source_cours:'§13'},

// IDIOMES TO BE (12)
{id:'itb-01',category:'Idiomes',level:'starter',type:'qcm',question:'"I am hungry" = :',options:["J'ai soif","J'ai sommeil","J'ai faim","J'ai peur"],answer_index:2,answer_text:"J'ai faim",hint:"Hungry = faim.",explication_fr:"To be hungry = avoir faim.",explication_en:"I AM hungry.",source_cours:'§24'},
{id:'itb-02',category:'Idiomes',level:'starter',type:'qcm',question:'"To be fed up with" = :',options:['avoir faim','en avoir marre de','avoir de la chance','avoir sommeil'],answer_index:1,answer_text:'en avoir marre de',hint:"Fed up = excédé.",explication_fr:"Fed up with = en avoir marre.",explication_en:"Fed up with = tired of.",source_cours:'§24'},
{id:'itb-03',category:'Idiomes',level:'starter',type:'qcm',question:'"She is ashamed" = :',options:['Elle a peur','Elle a honte','Elle a chaud','Elle est malade'],answer_index:1,answer_text:'Elle a honte',hint:"Ashamed = honte.",explication_fr:"Ashamed = avoir honte.",explication_en:"Ashamed = feeling shame.",source_cours:'§24'},
{id:'itb-04',category:'Idiomes',level:'starter',type:'qcm',question:'"To be seasick" = :',options:['avoir chaud','avoir le mal de mer','avoir peur','être pressé'],answer_index:1,answer_text:'avoir le mal de mer',hint:"Sea = mer.",explication_fr:"Seasick = mal de mer.",explication_en:"Seasick = ill on a boat.",source_cours:'§24'},
{id:'itb-05',category:'Idiomes',level:'starter',type:'qcm',question:'"I am thirsty" = :',options:["J'ai faim","J'ai froid","J'ai soif","J'ai sommeil"],answer_index:2,answer_text:"J'ai soif",hint:"Thirsty = soif.",explication_fr:"Thirsty = avoir soif.",explication_en:"I AM thirsty = I need a drink.",source_cours:'§24'},
{id:'itb-06',category:'Idiomes',level:'builder',type:'qcm',question:'"To be right" = :',options:['avoir tort','être à droite','avoir raison','être correct'],answer_index:2,answer_text:'avoir raison',hint:"Right ≠ wrong.",explication_fr:"To be right = avoir raison.",explication_en:"To be right = to be correct.",source_cours:'§24'},
{id:'itb-07',category:'Idiomes',level:'builder',type:'qcm',question:'"To be afraid of" = :',options:['avoir honte de','avoir peur de','être surpris de','être jaloux de'],answer_index:1,answer_text:'avoir peur de',hint:"Afraid = peur.",explication_fr:"Afraid of = avoir peur de.",explication_en:"To be afraid of = to fear.",source_cours:'§24'},
{id:'itb-08',category:'Idiomes',level:'builder',type:'lacune',question:'I am ___ of waiting.',answer_text:'tired',hint:"To be tired OF.",explication_fr:"Tired of = fatigué de.",explication_en:"Tired of + V-ing.",source_cours:'§24'},
{id:'itb-09',category:'Idiomes',level:'builder',type:'qcm',question:'"To be sleepy" = :',options:['être paresseux','avoir sommeil','être endormi','être fatigué'],answer_index:1,answer_text:'avoir sommeil',hint:"Sleepy = envie de dormir.",explication_fr:"Sleepy = avoir sommeil.",explication_en:"Sleepy = need to sleep.",source_cours:'§24'},
{id:'itb-10',category:'Idiomes',level:'starter',type:'qcm',question:'"To be lucky" = :',options:['être courageux','être en santé','avoir de la chance','être riche'],answer_index:2,answer_text:'avoir de la chance',hint:"Lucky = chanceux.",explication_fr:"Lucky = avoir de la chance.",explication_en:"Lucky = fortunate.",source_cours:'§24'},
{id:'itb-11',category:'Idiomes',level:'challenger',type:'traduction',question:'Traduire : "J\'en ai vraiment marre de la chaleur de Dakar."',answer_text:"I'm really fed up with the heat in Dakar.",hint:"Fed up WITH + nom.",explication_fr:"Fed up with the heat.",explication_en:"Fed up with the heat in Dakar.",source_cours:'§24'},
{id:'itb-12',category:'Idiomes',level:'builder',type:'qcm',question:'"I\'m starving" = :',options:["J'ai un peu faim","Je meurs de faim","J'ai soif","Je suis fatigué"],answer_index:1,answer_text:'Je meurs de faim',hint:"Starving = très faim.",explication_fr:"Starving = mourir de faim.",explication_en:"Starving = extremely hungry.",source_cours:'§19'},

// IDIOMES TO HAVE (12)
{id:'ith-01',category:'Idiomes To Have',level:'starter',type:'qcm',question:'"To have breakfast" = :',options:['déjeuner','dîner','petit-déjeuner','pause'],answer_index:2,answer_text:'petit-déjeuner',hint:"Break the fast.",explication_fr:"Breakfast = petit-déjeuner.",explication_en:"Breakfast = morning meal.",source_cours:'§17'},
{id:'ith-02',category:'Idiomes To Have',level:'starter',type:'qcm',question:'"To have a nap" = :',options:['prendre un bain','faire une sieste','prendre un repos','nager'],answer_index:1,answer_text:'faire une sieste',hint:"Nap = courte sieste.",explication_fr:"A nap = une sieste.",explication_en:"Have a nap = brief sleep.",source_cours:'§17'},
{id:'ith-03',category:'Idiomes To Have',level:'starter',type:'qcm',question:'"To have a bath" = :',options:['nager','se reposer','prendre un bain','douche'],answer_index:2,answer_text:'prendre un bain',hint:"Bath = baignoire.",explication_fr:"Have a bath = prendre un bain.",explication_en:"Have a bath = take a bath.",source_cours:'§17'},
{id:'ith-04',category:'Idiomes To Have',level:'builder',type:'qcm',question:'"To have a headache" = :',options:['mal de dos','mal de tête','mal au ventre','nausée'],answer_index:1,answer_text:'mal de tête',hint:"Head = tête.",explication_fr:"Headache = mal de tête.",explication_en:"Headache = pain in the head.",source_cours:'§17'},
{id:'ith-05',category:'Idiomes To Have',level:'builder',type:'qcm',question:'"To have a cold" = :',options:['avoir froid','avoir un rhume','avoir la grippe','de la fièvre'],answer_index:1,answer_text:'avoir un rhume',hint:"A cold = un rhume.",explication_fr:"A cold = un rhume.",explication_en:"Have a cold = be ill with a cold.",source_cours:'§17'},
{id:'ith-06',category:'Idiomes To Have',level:'builder',type:'qcm',question:'"To have a break" = :',options:['casser quelque chose','prendre une pause','une fracture','commencer'],answer_index:1,answer_text:'prendre une pause',hint:"Break = pause.",explication_fr:"Have a break = faire une pause.",explication_en:"Have a break = take a rest.",source_cours:'§17'},
{id:'ith-07',category:'Idiomes To Have',level:'builder',type:'qcm',question:'"To have a swim" = :',options:['avoir chaud','prendre une douche','aller nager','se reposer'],answer_index:2,answer_text:'aller nager',hint:"Swim = nager.",explication_fr:"Have a swim = aller nager.",explication_en:"Have a swim = go swimming.",source_cours:'§17'},
{id:'ith-08',category:'Idiomes To Have',level:'builder',type:'qcm',question:'"To have a stomachache" = :',options:['mal aux dents','mal à la gorge','mal au ventre','mal à la tête'],answer_index:2,answer_text:'mal au ventre',hint:"Stomach = ventre.",explication_fr:"Stomachache = mal au ventre.",explication_en:"Stomachache = stomach pain.",source_cours:'§17'},
{id:'ith-09',category:'Idiomes To Have',level:'starter',type:'qcm',question:'"Brunch" est :',options:['breakfast seul','lunch seul','breakfast + lunch','dessert'],answer_index:2,answer_text:'breakfast + lunch',hint:"Br(eakfast) + (l)unch.",explication_fr:"Brunch = breakfast + lunch.",explication_en:"Brunch = breakfast + lunch combined.",source_cours:'§17'},
{id:'ith-10',category:'Idiomes To Have',level:'builder',type:'lacune',question:'I have a ___. (mal de dos)',answer_text:'backache',hint:"Back = dos.",explication_fr:"Backache = mal de dos.",explication_en:"Backache = back pain.",source_cours:'§17'},
{id:'ith-11',category:'Idiomes To Have',level:'challenger',type:'traduction',question:'Traduire : "Ben a besoin de se reposer et de faire une sieste."',answer_text:"Ben needs to have a rest and a nap.",hint:"Have a rest + have a nap.",explication_fr:"Have a rest = se reposer.",explication_en:"Have a rest and a nap.",source_cours:'§17'},
{id:'ith-12',category:'Idiomes To Have',level:'builder',type:'qcm',question:'"I\'m swimmingly good" = :',options:['Je suis fatigué','Je vais très bien','Je nage bien','Je suis mouillé'],answer_index:1,answer_text:'Je vais très bien',hint:"Swimmingly = parfaitement.",explication_fr:"Swimmingly = parfaitement bien.",explication_en:"Going swimmingly = going very well.",source_cours:'§19'},

// INTRODUCTION (10)
{id:'intr-01',category:'Introduction',level:'starter',type:'qcm',question:'Comment introduit-on quelqu\'un ?',options:["My name is...","I go by...","Let me introduce you to...","Nice to meet you!"],answer_index:2,answer_text:'Let me introduce you to...',hint:'Présenter une autre personne.',explication_fr:"Let me introduce you to... = laisse-moi te présenter.",explication_en:"Let me introduce you to...",source_cours:'§20'},
{id:'intr-02',category:'Introduction',level:'starter',type:'qcm',question:'"Pleased to meet you!" est :',options:["Se présenter","Répondre à une présentation","Introduire qqn","Demander un nom"],answer_index:1,answer_text:'Répondre à une présentation',hint:"On répond.",explication_fr:"Pleased to meet you = réponse à une présentation.",explication_en:"Pleased to meet you = response to introduction.",source_cours:'§20'},
{id:'intr-03',category:'Introduction',level:'starter',type:'qcm',question:'"I go by the name of..." = :',options:["Je m'appelle...","Je préfère...","Je travaille comme...","Je vis à..."],answer_index:0,answer_text:"Je m'appelle...",hint:"Alternative à 'My name is'.",explication_fr:"I go by = je m'appelle (connu sous le nom de).",explication_en:"I go by the name of... = I am known as.",source_cours:'§20'},
{id:'intr-04',category:'Introduction',level:'starter',type:'qcm',question:'"Self employed" = :',options:['confiance en soi','développement perso','travailleur indépendant','libre service'],answer_index:2,answer_text:'travailleur indépendant',hint:"Self = soi-même.",explication_fr:"Self-employed = indépendant.",explication_en:"Self-employed = working for yourself.",source_cours:'§20'},
{id:'intr-05',category:'Introduction',level:'builder',type:'qcm',question:'"How do you do!" est :',options:['Entre amis','Présentation formelle','Demande de santé','En quittant'],answer_index:1,answer_text:'Présentation formelle',hint:"'How do you do?' = formel.",explication_fr:"How do you do! = réponse formelle.",explication_en:"How do you do! = formal response.",source_cours:'§20'},
{id:'intr-06',category:'Introduction',level:'builder',type:'lacune',question:'___ to meet you! (Ravi de vous rencontrer)',answer_text:'Nice',hint:"Nice/Pleased/Glad.",explication_fr:"Nice to meet you! = ravi de te rencontrer.",explication_en:"Nice to meet you!",source_cours:'§20'},
{id:'intr-07',category:'Introduction',level:'builder',type:'qcm',question:'"To get scarce" = :',options:['devenir célèbre','se faire rare','être pressé','trouver de la place'],answer_index:1,answer_text:'se faire rare',hint:"Diallo dit ça à Ben.",explication_fr:"To get scarce = se faire rare.",explication_en:"To get scarce = to disappear.",source_cours:'§21'},
{id:'intr-08',category:'Introduction',level:'challenger',type:'traduction',question:'Traduire : "Je voudrais vous présenter mon ami Abdou."',answer_text:"I would like you to meet my friend Abdou.",hint:"I would like you to meet...",explication_fr:"I would like you to meet = je voudrais vous présenter.",explication_en:"I would like you to meet...",source_cours:'§20'},
{id:'intr-09',category:'Introduction',level:'builder',type:'qcm',question:'"Self confidence" = :',options:['libre service','développement perso','confiance en soi','autonomie'],answer_index:2,answer_text:'confiance en soi',hint:"Confidence = confiance.",explication_fr:"Self-confidence = confiance en soi.",explication_en:"Self-confidence = belief in yourself.",source_cours:'§20'},
{id:'intr-10',category:'Introduction',level:'builder',type:'qcm',question:'"May I present you to..." est :',options:['informel','très formel','familier','rude'],answer_index:1,answer_text:'très formel',hint:"'May I' = très poli.",explication_fr:"May I present = très formel.",explication_en:"May I present = very formal.",source_cours:'§20'},

// LIKES & PREFERENCES (10)
{id:'lp-01',category:'Likes & Preferences',level:'builder',type:'qcm',question:'"I\'m mad about football" = :',options:["Je suis fou du football","Je déteste le football","Je joue au football","Je regarde"],answer_index:0,answer_text:'Je suis fou du football',hint:"Mad about = passionné par.",explication_fr:"Mad about = être fou de.",explication_en:"Mad about = very enthusiastic.",source_cours:'§4'},
{id:'lp-02',category:'Likes & Preferences',level:'builder',type:'qcm',question:'"I\'m keen on music" = :',options:["Je hais la musique","Je suis passionné de musique","Je joue","Je compose"],answer_index:1,answer_text:'Je suis passionné de musique',hint:"Keen on = enthousiaste.",explication_fr:"Keen on = passionné par.",explication_en:"Keen on = very interested in.",source_cours:'§4'},
{id:'lp-03',category:'Likes & Preferences',level:'builder',type:'qcm',question:'"I\'d rather watch TV" = :',options:["Je regarde souvent","Je préfère regarder","J'ai regardé","Je vais regarder"],answer_index:1,answer_text:'Je préfère regarder',hint:"I'd rather = je préférerais.",explication_fr:"I'd rather = je préférerais.",explication_en:"I'd rather + base verb = I prefer to.",source_cours:'§4'},
{id:'lp-04',category:'Likes & Preferences',level:'builder',type:'qcm',question:'"I\'m crazy about" = :',options:["Je suis en colère","Je suis fou de / j'adore","Je pense que c'est bizarre","J'évite"],answer_index:1,answer_text:"Je suis fou de / j'adore",hint:"Crazy about = très passionné.",explication_fr:"Crazy about = être fou de.",explication_en:"Crazy about = very enthusiastic.",source_cours:'§4'},
{id:'lp-05',category:'Likes & Preferences',level:'builder',type:'qcm',question:'"I\'m very fond of" = :',options:["J'ai peur de","J'apprécie beaucoup","Je déteste","Je suis habitué à"],answer_index:1,answer_text:"J'apprécie beaucoup",hint:"Fond of = affection.",explication_fr:"Fond of = apprécier beaucoup.",explication_en:"Fond of = having affection for.",source_cours:'§4'},
{id:'lp-06',category:'Likes & Preferences',level:'starter',type:'qcm',question:'"Hobby" = :',options:['Travail','Loisir / passe-temps','Voyage','Sport'],answer_index:1,answer_text:'Loisir / passe-temps',hint:"What do you do for fun?",explication_fr:"Hobby = passe-temps.",explication_en:"Hobby = leisure activity.",source_cours:'§4'},
{id:'lp-07',category:'Likes & Preferences',level:'builder',type:'qcm',question:'"I prefer reading to watching TV." — structure :',options:["Prefer + inf","Prefer + V-ing + to + V-ing","Prefer + nom","Prefer + that"],answer_index:1,answer_text:'Prefer + V-ing + to + V-ing',hint:"Prefer + V-ing + to + V-ing.",explication_fr:"I prefer + V-ing + TO + V-ing.",explication_en:"Prefer + V-ing + to + V-ing.",source_cours:'§4'},
{id:'lp-08',category:'Likes & Preferences',level:'builder',type:'qcm',question:'"Sci-fi" = :',options:['Science first','Science fiction','Scientific film','Science findings'],answer_index:1,answer_text:'Science fiction',hint:"Science + fiction.",explication_fr:"Sci-fi = science fiction.",explication_en:"Sci-fi = science fiction.",source_cours:'§4'},
{id:'lp-09',category:'Likes & Preferences',level:'challenger',type:'traduction',question:'Traduire : "Diallo est fou du football et préfère ça à la télé."',answer_text:"Diallo is mad about football and prefers it to watching TV.",hint:"Mad about + prefer it to.",explication_fr:"Mad about + prefer X to Y.",explication_en:"Mad about football, prefers it to watching TV.",source_cours:'§4-5'},
{id:'lp-10',category:'Likes & Preferences',level:'builder',type:'lacune',question:'I have a ___ for spicy food. (un faible pour)',answer_text:'spot',hint:"Have a spot for.",explication_fr:"Have a spot for = avoir un faible pour.",explication_en:"Have a spot for = weakness for.",source_cours:'§4'},

// VOCABULAIRE (20)
{id:'vo-01',category:'Vocabulaire',level:'builder',type:'qcm',question:'"Heat wave" = :',options:['vague de froid','canicule','pluie','chaleur normale'],answer_index:1,answer_text:'canicule',hint:"Heat = chaleur.",explication_fr:"Heat wave = canicule.",explication_en:"Heat wave = extreme heat.",source_cours:'§26'},
{id:'vo-02',category:'Vocabulaire',level:'builder',type:'qcm',question:'"To postpone" = :',options:['annuler','avancer','reporter','confirmer'],answer_index:2,answer_text:'reporter',hint:"Post = après.",explication_fr:"Postpone = reporter.",explication_en:"Postpone = delay.",source_cours:'§7'},
{id:'vo-03',category:'Vocabulaire',level:'builder',type:'qcm',question:'"To find out" = :',options:['chercher','découvrir','perdre','oublier'],answer_index:1,answer_text:'découvrir',hint:"Learn an information.",explication_fr:"Find out = découvrir.",explication_en:"Find out = to discover.",source_cours:'§7'},
{id:'vo-04',category:'Vocabulaire',level:'builder',type:'qcm',question:'"Day-off" = :',options:['heure supp.','jour de congé','journée travail','jour férié'],answer_index:1,answer_text:'jour de congé',hint:"Off = pas de travail.",explication_fr:"Day-off = jour de congé.",explication_en:"Day-off = day without work.",source_cours:'§7'},
{id:'vo-05',category:'Vocabulaire',level:'starter',type:'qcm',question:'"Luggage" = :',options:['billet','bagage','passeport','voiture'],answer_index:1,answer_text:'bagage',hint:"Emma part à Liverpool.",explication_fr:"Luggage = bagages.",explication_en:"Luggage = bags and suitcases.",source_cours:'§3'},
{id:'vo-06',category:'Vocabulaire',level:'builder',type:'qcm',question:'"To assist" = :',options:["assister à","aider","diriger","participer"],answer_index:1,answer_text:'aider',hint:"Faux ami !",explication_fr:"Assist = aider (faux ami).",explication_en:"Assist = to help (false friend).",source_cours:'§7'},
{id:'vo-07',category:'Vocabulaire',level:'builder',type:'qcm',question:'"Obviously" = :',options:['parfois','évidemment','rapidement','surtout'],answer_index:1,answer_text:'évidemment',hint:"Of course.",explication_fr:"Obviously = évidemment.",explication_en:"Obviously = clearly.",source_cours:'§3'},
{id:'vo-08',category:'Vocabulaire',level:'builder',type:'qcm',question:'"Until" / "Till" = :',options:['depuis','pendant',"jusqu'à",'avant'],answer_index:2,answer_text:"jusqu'à",hint:"Up to a point in time.",explication_fr:"Until/Till = jusqu'à.",explication_en:"Until/Till = up to.",source_cours:'§7'},
{id:'vo-09',category:'Vocabulaire',level:'builder',type:'qcm',question:'"Go ahead" = :',options:['reculer','attendre','allez-y','s\'arrêter'],answer_index:2,answer_text:'allez-y',hint:"Proceed.",explication_fr:"Go ahead = allez-y.",explication_en:"Go ahead = proceed.",source_cours:'§7'},
{id:'vo-10',category:'Vocabulaire',level:'builder',type:'qcm',question:'"Pilgrimage" = :',options:["voyage d'affaires","tourisme","pèlerinage","escapade"],answer_index:2,answer_text:'pèlerinage',hint:"Emma à Liverpool.",explication_fr:"Pilgrimage = pèlerinage.",explication_en:"Pilgrimage = religious journey.",source_cours:'§3'},
{id:'vo-11',category:'Vocabulaire',level:'builder',type:'qcm',question:'"Seat belt" = :',options:['ceinture sécurité','siège','portière','tableau de bord'],answer_index:0,answer_text:'ceinture sécurité',hint:"Obligatoire en voiture.",explication_fr:"Seat belt = ceinture de sécurité.",explication_en:"Seat belt = safety belt.",source_cours:'§18'},
{id:'vo-12',category:'Vocabulaire',level:'starter',type:'qcm',question:'"I\'m fasting" = :',options:['Je mange beaucoup','Je jeûne','Je suis pressé','Je suis fatigué'],answer_index:1,answer_text:'Je jeûne',hint:"Fast = jeûner.",explication_fr:"Fasting = jeûner (Ramadan).",explication_en:"Fasting = not eating.",source_cours:'§18'},
{id:'vo-13',category:'Vocabulaire',level:'builder',type:'qcm',question:'"By the way" = :',options:['de toute façon','au fait','tout de suite','de ce côté'],answer_index:1,answer_text:'au fait',hint:"Intro à une remarque.",explication_fr:"By the way = au fait.",explication_en:"By the way = incidentally.",source_cours:'§16'},
{id:'vo-14',category:'Vocabulaire',level:'builder',type:'qcm',question:'"To protect" = :',options:['attaquer','protéger','inviter','fermer'],answer_index:1,answer_text:'protéger',hint:"Même racine que protection.",explication_fr:"Protect = protéger.",explication_en:"To protect = to keep safe.",source_cours:'§7'},
{id:'vo-15',category:'Vocabulaire',level:'builder',type:'qcm',question:'"Lunchbox" = :',options:['restaurant','boîte à repas','pause déjeuner','menu'],answer_index:1,answer_text:'boîte à repas',hint:"Box = boîte.",explication_fr:"Lunchbox = boîte à repas.",explication_en:"Lunchbox = packed lunch container.",source_cours:'§18'},
{id:'vo-16',category:'Vocabulaire',level:'builder',type:'qcm',question:'"Deadline" = :',options:['réunion','date limite','contrat','fiche de paie'],answer_index:1,answer_text:'date limite',hint:"The last possible date.",explication_fr:"Deadline = date limite.",explication_en:"Deadline = final date.",source_cours:'Vocabulaire'},
{id:'vo-17',category:'Vocabulaire',level:'builder',type:'qcm',question:'"Colleague" = :',options:['supérieur','subordonné','collègue','client'],answer_index:2,answer_text:'collègue',hint:"Same level at work.",explication_fr:"Colleague = collègue.",explication_en:"Colleague = workmate.",source_cours:'Vocabulaire'},
{id:'vo-18',category:'Vocabulaire',level:'builder',type:'qcm',question:'"Siblings" = :',options:['parents','frères et sœurs','amis','enfants'],answer_index:1,answer_text:'frères et sœurs',hint:"Brothers AND sisters.",explication_fr:"Siblings = frères et sœurs.",explication_en:"Siblings = brothers and sisters.",source_cours:'Vocabulaire'},
{id:'vo-19',category:'Vocabulaire',level:'challenger',type:'traduction',question:'Traduire : "Il y a un embouteillage sur la route de Touba."',answer_text:"There is a traffic jam on the road to Touba.",hint:"Traffic jam.",explication_fr:"There IS + traffic jam.",explication_en:"There is a traffic jam.",source_cours:'Vocabulaire §15'},
{id:'vo-20',category:'Vocabulaire',level:'builder',type:'qcm',question:'"To postpone" → utilisé dans :',options:['la conversation de Liverpool','la conversation de Saint-Louis','la conversation de shopping','la conversation de foot'],answer_index:2,answer_text:'la conversation de shopping',hint:"Emma et Diallo reportent un RDV.",explication_fr:"Emma postpones her shopping trip with Diallo.",explication_en:"Emma postpones her shopping appointment.",source_cours:'§8'},

// PRÉSENT SIMPLE (10)
{id:'prs-01',category:'Present Simple',level:'starter',type:'qcm',question:'On utilise le Present Simple pour :',options:['action en cours','habitude / vérité générale','action future planifiée','action passée récente'],answer_index:1,answer_text:'habitude / vérité générale',hint:"Habitude ou fait général.",explication_fr:"Present Simple = habitude, vérité.",explication_en:"Present Simple = habits and truths.",source_cours:'Present Simple'},
{id:'prs-02',category:'Present Simple',level:'starter',type:'qcm',question:'Terminaison 3ème pers. sing. :',options:['-ing','-ed','-s / -es','rien'],answer_index:2,answer_text:'-s / -es',hint:"He works, she goes.",explication_fr:"He/She/It → +S ou +ES.",explication_en:"3rd person: + s or + es.",source_cours:'Present Simple'},
{id:'prs-03',category:'Present Simple',level:'starter',type:'qcm',question:'Forme négative correcte :',options:["She not work","She doesn't works","She doesn't work","She don't work"],answer_index:2,answer_text:"She doesn't work",hint:"DOESN'T + base.",explication_fr:"DOESN'T + base verbale.",explication_en:"She DOESN'T WORK.",source_cours:'Present Simple'},
{id:'prs-04',category:'Present Simple',level:'starter',type:'lacune',question:'He ___ (like) chocolate.',answer_text:'likes',hint:"3ème pers. → +S.",explication_fr:"He → LIKES.",explication_en:"He LIKES.",source_cours:'Present Simple'},
{id:'prs-05',category:'Present Simple',level:'builder',type:'qcm',question:'Question correcte :',options:["Do he work here?","Does he works here?","Does he work here?","Is he work here?"],answer_index:2,answer_text:'Does he work here?',hint:"DOES + base.",explication_fr:"DOES + he + work (base).",explication_en:"Does he work?",source_cours:'Present Simple'},
{id:'prs-06',category:'Present Simple',level:'builder',type:'lacune',question:'She ___ (not / eat) meat.',answer_text:"doesn't eat",hint:"She → doesn't.",explication_fr:"DOESN'T + eat.",explication_en:"She DOESN'T EAT.",source_cours:'Present Simple'},
{id:'prs-07',category:'Present Simple',level:'builder',type:'qcm',question:'"She ___ (study) every day." :',options:['studys','studies','study','studyes'],answer_index:1,answer_text:'studies',hint:"Y → IES après consonne.",explication_fr:"Study → STUDIES.",explication_en:"Study → STUDIES.",source_cours:'Present Simple'},
{id:'prs-08',category:'Present Simple',level:'builder',type:'qcm',question:'"He ___ (go) to school." :',options:['gos','go','goes','going'],answer_index:2,answer_text:'goes',hint:"Go → GOES.",explication_fr:"Go → GOES.",explication_en:"Go → GOES.",source_cours:'Present Simple'},
{id:'prs-09',category:'Present Simple',level:'challenger',type:'traduction',question:'Traduire : "Fatou ne mange pas de viande le vendredi."',answer_text:"Fatou doesn't eat meat on Fridays.",hint:"DOESN'T + On Fridays.",explication_fr:"DOESN'T eat. On Fridays = habitude.",explication_en:"Fatou doesn't eat meat on Fridays.",source_cours:'Present Simple'},
{id:'prs-10',category:'Present Simple',level:'builder',type:'qcm',question:'"He teaches" — pourquoi +es ?',options:["Tous les verbes","Après ch/sh/x/z/o","C'est irrégulier","C'est poli"],answer_index:1,answer_text:'Après ch/sh/x/z/o',hint:"Teach se termine par CH.",explication_fr:"Après ch/sh/x/z/o → +es.",explication_en:"After ch/sh/x/z/o → +es.",source_cours:'Present Simple'},

// SAISONS (8)
{id:'sai-01',category:'Saisons',level:'starter',type:'qcm',question:'Saison après "autumn" :',options:['Spring','Summer','Winter','Rainy season'],answer_index:2,answer_text:'Winter',hint:"Autumn → Winter.",explication_fr:"Autumn → Winter.",explication_en:"Autumn → Winter.",source_cours:'§25'},
{id:'sai-02',category:'Saisons',level:'starter',type:'qcm',question:'"Rainy season" = :',options:['Saison sèche','Saison des pluies','Été','Hiver'],answer_index:1,answer_text:'Saison des pluies',hint:"Rainy = pluvieux.",explication_fr:"Rainy season = hivernage.",explication_en:"Rainy season = wet season.",source_cours:'§25'},
{id:'sai-03',category:'Saisons',level:'starter',type:'qcm',question:'"Summer" = :',options:['Printemps','Été','Automne','Hiver'],answer_index:1,answer_text:'Été',hint:"La saison la plus chaude.",explication_fr:"Summer = été.",explication_en:"Summer = hottest season.",source_cours:'§25'},
{id:'sai-04',category:'Saisons',level:'starter',type:'qcm',question:'"Spring" = :',options:['Été','Automne','Printemps','Hiver'],answer_index:2,answer_text:'Printemps',hint:"Saison des fleurs.",explication_fr:"Spring = printemps.",explication_en:"Spring = after winter.",source_cours:'§25'},
{id:'sai-05',category:'Saisons',level:'builder',type:'qcm',question:'"Outdoors" = :',options:['dedans','dehors','partout','nulle part'],answer_index:1,answer_text:'dehors',hint:"Out = dehors.",explication_fr:"Outdoors = dehors.",explication_en:"Outdoors = outside.",source_cours:'§26'},
{id:'sai-06',category:'Saisons',level:'builder',type:'qcm',question:'"Left-handed" = :',options:['droitier','gaucher','ambidextre','maladroit'],answer_index:1,answer_text:'gaucher',hint:"Left = gauche.",explication_fr:"Left-handed = gaucher.",explication_en:"Left-handed = using the left hand.",source_cours:'§26'},
{id:'sai-07',category:'Saisons',level:'builder',type:'qcm',question:'"Dry season" correspond au Sénégal à :',options:["L'hivernage","Saison sèche nov.-mai","L'été seul","Janvier seul"],answer_index:1,answer_text:'Saison sèche nov.-mai',hint:"Dry = sec.",explication_fr:"Dry season = saison sèche.",explication_en:"Dry season = no rain.",source_cours:'§25'},
{id:'sai-08',category:'Saisons',level:'builder',type:'traduction',question:'Traduire : "Il fait très chaud dehors aujourd\'hui."',answer_text:"It is very hot outdoors today.",hint:"To be hot.",explication_fr:"It is hot = il fait chaud.",explication_en:"It is very hot outdoors today.",source_cours:'§26'},

// VERBES IRRÉGULIERS (10)
{id:'vi-01',category:'Verbes Irréguliers',level:'builder',type:'qcm',question:'Passé simple de "give" :',options:['gived','gave','given','gives'],answer_index:1,answer_text:'gave',hint:"Give/gave/given.",explication_fr:"Give → GAVE.",explication_en:"Give → GAVE.",source_cours:'§30'},
{id:'vi-02',category:'Verbes Irréguliers',level:'builder',type:'qcm',question:'Passé simple de "speak" :',options:['speaked','spake','spoke','spoken'],answer_index:2,answer_text:'spoke',hint:"Speak/spoke/spoken.",explication_fr:"Speak → SPOKE.",explication_en:"Speak → SPOKE.",source_cours:'§30'},
{id:'vi-03',category:'Verbes Irréguliers',level:'builder',type:'qcm',question:'Passé simple de "think" :',options:['thinked','thought','thunk','thinks'],answer_index:1,answer_text:'thought',hint:"Think/thought/thought.",explication_fr:"Think → THOUGHT.",explication_en:"Think → THOUGHT.",source_cours:'§30'},
{id:'vi-04',category:'Verbes Irréguliers',level:'builder',type:'qcm',question:'PP de "write" :',options:['writed','wrote','written','writing'],answer_index:2,answer_text:'written',hint:"Write/wrote/written.",explication_fr:"Write → wrote → WRITTEN.",explication_en:"Write → wrote → WRITTEN.",source_cours:'§30'},
{id:'vi-05',category:'Verbes Irréguliers',level:'builder',type:'qcm',question:'Passé simple de "meet" :',options:['meeted','met','meet','meats'],answer_index:1,answer_text:'met',hint:"Meet/met/met.",explication_fr:"Meet → MET.",explication_en:"Meet → MET.",source_cours:'§30'},
{id:'vi-06',category:'Verbes Irréguliers',level:'builder',type:'qcm',question:'Passé simple de "run" :',options:['runned','ran','run','ranned'],answer_index:1,answer_text:'ran',hint:"Run/ran/run.",explication_fr:"Run → RAN.",explication_en:"Run → RAN.",source_cours:'§30'},
{id:'vi-07',category:'Verbes Irréguliers',level:'builder',type:'qcm',question:'Passé simple de "send" :',options:['sended','sent','send','sends'],answer_index:1,answer_text:'sent',hint:"Send/sent/sent.",explication_fr:"Send → SENT.",explication_en:"Send → SENT.",source_cours:'§30'},
{id:'vi-08',category:'Verbes Irréguliers',level:'builder',type:'qcm',question:'PP de "eat" :',options:['eated','ate','eaten','eating'],answer_index:2,answer_text:'eaten',hint:"Eat/ate/eaten.",explication_fr:"Eat → ate → EATEN.",explication_en:"Eat → ate → EATEN.",source_cours:'§30'},
{id:'vi-09',category:'Verbes Irréguliers',level:'builder',type:'qcm',question:'Passé simple de "win" :',options:['wined','won','wind','wins'],answer_index:1,answer_text:'won',hint:"Win/won/won.",explication_fr:"Win → WON.",explication_en:"Win → WON.",source_cours:'§30'},
{id:'vi-10',category:'Verbes Irréguliers',level:'builder',type:'qcm',question:'Passé simple de "lose" :',options:['losed','losted','lost','lose'],answer_index:2,answer_text:'lost',hint:"Lose/lost/lost.",explication_fr:"Lose → LOST.",explication_en:"Lose → LOST.",source_cours:'§30'},

// ══ VOCABULAIRE SUPPLÉMENTAIRE (10) ════════════════════════════
{id:'vx-01',category:'Vocabulaire',level:'builder',type:'qcm',question:'"Crowded" = :',options:['désert','bondé','calme','bruyant'],answer_index:1,answer_text:'bondé',hint:'Plein de monde.',explication_fr:"Crowded = bondé, plein de monde.",explication_en:"Crowded = full of people.",source_cours:'§12'},
{id:'vx-02',category:'Vocabulaire',level:'starter',type:'qcm',question:'"Hungry" = :',options:['fatigué','assoiffé','affamé','pressé'],answer_index:2,answer_text:'affamé',hint:"Hungry = faim.",explication_fr:"Hungry = avoir faim.",explication_en:"Hungry = feeling the need to eat.",source_cours:'§24'},
{id:'vx-03',category:'Vocabulaire',level:'builder',type:'qcm',question:'"To miss" = :',options:['frapper','manquer / rater','perdre','chercher'],answer_index:1,answer_text:'manquer / rater',hint:"I miss you = tu me manques.",explication_fr:"Miss = manquer (sentiment) ou rater (bus, cours).",explication_en:"Miss = to feel the absence of OR to fail to catch.",source_cours:'Vocabulaire'},
{id:'vx-04',category:'Vocabulaire',level:'builder',type:'qcm',question:'"Fluent in English" signifie :',options:["débutant en anglais","courant en anglais","silencieux en anglais","timide en anglais"],answer_index:1,answer_text:'courant en anglais',hint:"Fluent = parler couramment.",explication_fr:"Fluent = parler couramment, sans difficulté.",explication_en:"Fluent = able to speak smoothly and easily.",source_cours:'Vocabulaire'},
{id:'vx-05',category:'Vocabulaire',level:'builder',type:'qcm',question:'"To be on time" = :',options:["être en retard","être en avance","être à l'heure","être pressé"],answer_index:2,answer_text:"être à l'heure",hint:"On time = pile à l'heure.",explication_fr:"On time = à l'heure. Late = en retard. Early = en avance.",explication_en:"On time = not late and not early — punctual.",source_cours:'Vocabulaire'},
{id:'vx-06',category:'Vocabulaire',level:'builder',type:'qcm',question:'"Abroad" = :',options:['à la maison','en ville','à l\'étranger','au marché'],answer_index:2,answer_text:"à l'étranger",hint:"Emma voyage abroad.",explication_fr:"Abroad = à l'étranger, en dehors du pays.",explication_en:"Abroad = in or to a foreign country.",source_cours:'Vocabulaire'},
{id:'vx-07',category:'Vocabulaire',level:'builder',type:'qcm',question:'"To afford" = :',options:['offrir','avoir les moyens de','refuser','préférer'],answer_index:1,answer_text:'avoir les moyens de',hint:"Can you afford it?",explication_fr:"Afford = avoir les moyens financiers de.",explication_en:"To afford = to have enough money for.",source_cours:'Vocabulaire'},
{id:'vx-08',category:'Present Simple',level:'builder',type:'lacune',question:'Water ___ (boil) at 100°C.',answer_text:'boils',hint:"Vérité générale → présent simple.",explication_fr:"Vérité générale → Present Simple. Water BOILS.",explication_en:"General truth → Present Simple. Water BOILS.",source_cours:'Present Simple'},
{id:'vx-09',category:'Past Simple',level:'starter',type:'qcm',question:'Passé de "make" :',options:['maked','made','maded','makes'],answer_index:1,answer_text:'made',hint:"Make/made/made.",explication_fr:"Make → MADE (irrégulier).",explication_en:"Make → MADE → made.",source_cours:'§30'},
{id:'vx-10',category:'Beaucoup',level:'challenger',type:'traduction',question:'Traduire : "Elle a trop de travail cette semaine."',answer_text:'She has too much work this week.',hint:"Too much + indénombrable.",explication_fr:"TOO MUCH + work (indénombrable).",explication_en:"She has too much work — uncountable noun.",source_cours:'§13'},
];

// ─── FONCTIONS D'ACCÈS AU POOL ────────────────────────────────

/** Retourne toutes les catégories uniques du pool. */
function getAllCategories() {
  return [...new Set(QUESTION_POOL.map(q => q.category))];
}

/** Retourne le nombre de questions statiques pour une catégorie. */
function getPoolSizeForCategory(category) {
  return QUESTION_POOL.filter(q => q.category === category).length;
}

/** Retourne toutes les questions d'une catégorie filtrées par niveau. */
function getQuestionsForCategory(category, level) {
  const order = { starter: 0, builder: 1, challenger: 2 };
  const maxLevel = order[level] ?? 1;
  return QUESTION_POOL.filter(q =>
    q.category === category &&
    (order[q.level] ?? 0) <= maxLevel
  );
}

/** Retourne une question non encore posée pour une catégorie/niveau. */
function pickQuestion(category, level, askedIds = []) {
  const candidates = getQuestionsForCategory(category, level)
    .filter(q => !askedIds.includes(q.id));
  if (candidates.length === 0) return null;
  return candidates[Math.floor(Math.random() * candidates.length)];
}
