// questionPool_es.js — CTI English PWA — Pool espagnol
// Structure identique au pool anglais :
// { id, category, level, type, question, options[], answer_index,
//   answer_text, hint, explication_fr, explication_en (→ explication ES ici), source_cours }
// explication_fr = explication en français | explication_en = explication en espagnol
'use strict';

const QUESTION_POOL_ES = [

// ══ SER / ESTAR (12) ══════════════════════════════════════════
{id:'es-se-01',category:'Ser / Estar',level:'starter',type:'qcm',
 question:'Comment dit-on "Je suis étudiant(e)" ?',
 options:['Estoy estudiante','Soy estudiante','Tengo estudiante','Hago estudiante'],
 answer_index:1,answer_text:'Soy estudiante',
 hint:'Profession → SER.',
 explication_fr:'SER = identité permanente (profession, nationalité, origine).',
 explication_en:'SER = identidad permanente. Soy estudiante.'},

{id:'es-se-02',category:'Ser / Estar',level:'starter',type:'qcm',
 question:'Comment dit-on "Je suis fatigué(e)" ?',
 options:['Soy cansado','Estoy cansado','Tengo cansado','Hay cansado'],
 answer_index:1,answer_text:'Estoy cansado',
 hint:'État temporaire → ESTAR.',
 explication_fr:'ESTAR = état temporaire (fatigue, humeur, position).',
 explication_en:'ESTAR = estado temporal. Estoy cansado/a.'},

{id:'es-se-03',category:'Ser / Estar',level:'starter',type:'qcm',
 question:'"¿Dónde está el mercado?" signifie :',
 options:['Qui est au marché ?','Où est le marché ?','Comment est le marché ?','Quand est le marché ?'],
 answer_index:1,answer_text:'Où est le marché ?',
 hint:'Dónde = où.',
 explication_fr:'ESTAR exprime la localisation. ¿Dónde está? = Où est ?',
 explication_en:'ESTAR para la ubicación. ¿Dónde está? = ¿En qué lugar?'},

{id:'es-se-04',category:'Ser / Estar',level:'builder',type:'qcm',
 question:'Phrase correcte pour "La réunion est à 9h" :',
 options:['La reunión está a las 9','La reunión es a las 9','La reunión tiene a las 9','La reunión hace a las 9'],
 answer_index:1,answer_text:'La reunión es a las 9',
 hint:'Événement programmé → SER.',
 explication_fr:'SER pour les événements planifiés (heure, date, lieu d\'un événement).',
 explication_en:'SER para eventos programados. La reunión es a las 9.'},

{id:'es-se-05',category:'Ser / Estar',level:'builder',type:'qcm',
 question:'"Diallo está en Dakar" signifie :',
 options:['Diallo est de Dakar','Diallo est à Dakar','Diallo va à Dakar','Diallo habite Dakar'],
 answer_index:1,answer_text:'Diallo est à Dakar',
 hint:'Está = localisation.',
 explication_fr:'ESTAR + localisation = être quelque part (temporaire).',
 explication_en:'ESTAR + lugar = ubicación temporal. Está en Dakar.'},

{id:'es-se-06',category:'Ser / Estar',level:'builder',type:'lacune',
 question:'El café ___ frío hoy.',
 answer_text:'está',
 hint:'Température → état temporaire.',
 explication_fr:'Température = état temporaire → ESTAR.',
 explication_en:'Temperatura = estado temporal → ESTAR. El café está frío.'},

{id:'es-se-07',category:'Ser / Estar',level:'starter',type:'qcm',
 question:'"Soy de Dakar" signifie :',
 options:["Je suis à Dakar","Je viens de Dakar","Je pars de Dakar","Je connais Dakar"],
 answer_index:1,answer_text:'Je viens de Dakar',
 hint:'SER + de = origine.',
 explication_fr:'SER + DE = origine. Soy de Dakar = Je suis originaire de Dakar.',
 explication_en:'SER + de = origen. Soy de Dakar = Soy originario de Dakar.'},

{id:'es-se-08',category:'Ser / Estar',level:'builder',type:'qcm',
 question:'Forme correcte : "Emma ___ muy contenta hoy."',
 options:['es','ser','está','tiene'],
 answer_index:2,answer_text:'está',
 hint:'Humeur = état temporaire.',
 explication_fr:'Humeur/émotion = état temporaire → ESTAR.',
 explication_en:'Emoción = estado temporal → ESTAR. Emma está contenta.'},

{id:'es-se-09',category:'Ser / Estar',level:'challenger',type:'traduction',
 question:'Traduire : "La conférence est importante et elle commence à 10h."',
 answer_text:'La conferencia es importante y empieza a las 10.',
 hint:'Important (permanent) = SER / Heure événement = SER.',
 explication_fr:'SER pour caractéristique permanente + heure d\'événement.',
 explication_en:'SER para característica + hora de evento. Es importante, empieza a las 10.'},

{id:'es-se-10',category:'Ser / Estar',level:'challenger',type:'qcm',
 question:'"Estás listo para el examen?" — réponse correcte :',
 options:['Sí, soy listo.','Sí, estoy listo.','Sí, tengo listo.','Sí, hay listo.'],
 answer_index:1,answer_text:'Sí, estoy listo.',
 hint:'Prêt = état temporaire.',
 explication_fr:'Listo avec ESTAR = prêt. Listo avec SER = intelligent.',
 explication_en:'Listo + ESTAR = preparado. Listo + SER = inteligente.'},

{id:'es-se-11',category:'Ser / Estar',level:'starter',type:'qcm',
 question:'"¿Cómo estás?" signifie :',
 options:['Qui es-tu ?','Comment tu es (état) ?','D\'où es-tu ?','Que fais-tu ?'],
 answer_index:1,answer_text:'Comment tu es (état) ?',
 hint:'Cómo + estar = état.',
 explication_fr:'¿Cómo estás? = Comment vas-tu ? (état momentané).',
 explication_en:'¿Cómo estás? = ¿Cómo te encuentras ahora?'},

{id:'es-se-12',category:'Ser / Estar',level:'builder',type:'lacune',
 question:'Nosotros ___ profesores en CTI.',
 answer_text:'somos',
 hint:'Profession → SER / nosotros.',
 explication_fr:'Profession permanente → SER. Nosotros SOMOS.',
 explication_en:'Profesión → SER. Nosotros somos profesores.'},

// ══ TENER (10) ════════════════════════════════════════════════
{id:'es-te-01',category:'Tener',level:'starter',type:'qcm',
 question:'Comment dit-on "J\'ai faim" ?',
 options:['Estoy hambre','Soy hambre','Tengo hambre','Hago hambre'],
 answer_index:2,answer_text:'Tengo hambre',
 hint:'Sensations physiques → TENER.',
 explication_fr:'Sensations (faim, soif, froid, chaud, peur) → TENER en espagnol.',
 explication_en:'Sensaciones físicas → TENER. Tengo hambre / sed / frío / calor.'},

{id:'es-te-02',category:'Tener',level:'starter',type:'qcm',
 question:'"Tengo 20 años" signifie :',
 options:["J'ai 20 ans","Je suis âgé de 20","J'avais 20 ans","Je ferai 20 ans"],
 answer_index:0,answer_text:"J'ai 20 ans",
 hint:'Âge → TENER en espagnol.',
 explication_fr:'Âge → TENER (pas SER). Tengo 20 años.',
 explication_en:'Edad → TENER. Tengo 20 años = Tengo esa cantidad de años.'},

{id:'es-te-03',category:'Tener',level:'starter',type:'lacune',
 question:'Ella ___ una reunión a las 3.',
 answer_text:'tiene',
 hint:'He/She/It → tiene.',
 explication_fr:'TENER : yo tengo / tú tienes / él-ella TIENE.',
 explication_en:'TENER: yo tengo, tú tienes, él/ella TIENE.'},

{id:'es-te-04',category:'Tener',level:'builder',type:'qcm',
 question:'"Tener prisa" signifie :',
 options:['avoir de la place','être pressé','avoir une idée','avoir peur'],
 answer_index:1,answer_text:'être pressé',
 hint:'Prisa = précipitation.',
 explication_fr:'Tener prisa = être pressé (très courant).',
 explication_en:'Tener prisa = estar apurado.'},

{id:'es-te-05',category:'Tener',level:'builder',type:'qcm',
 question:'"¿Tienes tiempo?" signifie :',
 options:['As-tu le temps ?','Es-tu disponible ?','As-tu faim ?','As-tu froid ?'],
 answer_index:0,answer_text:'As-tu le temps ?',
 hint:'Tiempo ici = le temps (disponibilité).',
 explication_fr:'¿Tienes tiempo? = As-tu du temps disponible ?',
 explication_en:'¿Tienes tiempo? = ¿Dispones de tiempo ahora?'},

{id:'es-te-06',category:'Tener',level:'builder',type:'qcm',
 question:'Phrase correcte : "Ils n\'ont pas de réseau."',
 options:['No tienen red','No están red','No son red','No hay su red'],
 answer_index:0,answer_text:'No tienen red',
 hint:'Ils/Elles → tienen.',
 explication_fr:'Ils n\'ont pas → NO TIENEN.',
 explication_en:'Ellos no tienen red = They have no network.'},

{id:'es-te-07',category:'Tener',level:'builder',type:'lacune',
 question:'¿___ vosotros los documentos?',
 answer_text:'Tenéis',
 hint:'Vosotros → tenéis.',
 explication_fr:'Vosotros → TENÉIS (forme espagnole Espagne).',
 explication_en:'Vosotros tenéis = ustedes tienen (América).'},

{id:'es-te-08',category:'Tener',level:'challenger',type:'traduction',
 question:'Traduire : "Emma n\'a pas les résultats du test."',
 answer_text:'Emma no tiene los resultados del test.',
 hint:'No + verbe conjugué.',
 explication_fr:'Négation simple : NO + verbe. Emma no TIENE.',
 explication_en:'Negación: NO + verbo. Emma no tiene los resultados.'},

{id:'es-te-09',category:'Tener',level:'starter',type:'qcm',
 question:'"Tener miedo" signifie :',
 options:['avoir honte','avoir froid','avoir peur','avoir chaud'],
 answer_index:2,answer_text:'avoir peur',
 hint:'Miedo = peur.',
 explication_fr:'Tener miedo = avoir peur.',
 explication_en:'Tener miedo = sentir miedo, temer algo.'},

{id:'es-te-10',category:'Tener',level:'builder',type:'qcm',
 question:'"Tener razón" signifie :',
 options:["avoir l'air","avoir raison","avoir tort","avoir besoin"],
 answer_index:1,answer_text:'avoir raison',
 hint:'Razón = raison.',
 explication_fr:'Tener razón = avoir raison. Très courant.',
 explication_en:'Tener razón = estar en lo correcto.'},

// ══ PRÉSENT INDICATIF (10) ════════════════════════════════════
{id:'es-pi-01',category:'Présent',level:'starter',type:'qcm',
 question:'Conjugaison de "hablar" (parler) à "yo" :',
 options:['hablo','hablas','habla','hablamos'],
 answer_index:0,answer_text:'hablo',
 hint:'Yo → -o pour les verbes en -AR.',
 explication_fr:'Verbes en -AR : yo HABLO, tú hablas, él habla.',
 explication_en:'Verbos en -AR: yo HABLO, tú hablas, él/ella habla.'},

{id:'es-pi-02',category:'Présent',level:'starter',type:'qcm',
 question:'"¿Habláis español?" — "habláis" est :',
 options:['je parle','tu parles','vous parlez (Espagne)','ils parlent'],
 answer_index:2,answer_text:'vous parlez (Espagne)',
 hint:'Vosotros → -áis.',
 explication_fr:'Vosotros HABLÁIS = vous parlez (usage espagnol).',
 explication_en:'Vosotros habláis. En América: ustedes hablan.'},

{id:'es-pi-03',category:'Présent',level:'starter',type:'lacune',
 question:'Ellos ___ (trabajar) mucho.',
 answer_text:'trabajan',
 hint:'Ellos → -an pour -AR.',
 explication_fr:'Ellos/ellas/ustedes → -AN pour les verbes en -AR.',
 explication_en:'Ellos/Ellas → trabajan. Terminación -an (verbos -AR).'},

{id:'es-pi-04',category:'Présent',level:'builder',type:'qcm',
 question:'"Vivir" (vivre) à "nosotros" :',
 options:['vivamos','vivemos','vivimos','vivamos'],
 answer_index:2,answer_text:'vivimos',
 hint:'Verbes en -IR, nosotros → -imos.',
 explication_fr:'Verbes en -IR : nosotros VIVIMOS.',
 explication_en:'Verbos en -IR: nosotros VIVIMOS.'},

{id:'es-pi-05',category:'Présent',level:'builder',type:'qcm',
 question:'Verbe irrégulier : "yo" de "ir" (aller) :',
 options:['ío','voy','igo','vamos'],
 answer_index:1,answer_text:'voy',
 hint:'Ir est très irrégulier.',
 explication_fr:'IR : yo VOY, tú vas, él va, nosotros vamos.',
 explication_en:'IR (verbo irregular): yo VOY, tú vas, él va.'},

{id:'es-pi-06',category:'Présent',level:'builder',type:'qcm',
 question:'"Diallo hace su trabajo" signifie :',
 options:["Diallo fait son travail","Diallo a son travail","Diallo a fait son travail","Diallo fera son travail"],
 answer_index:0,answer_text:'Diallo fait son travail',
 hint:'Hacer = faire.',
 explication_fr:'Hacer = faire. Hace = il/elle fait.',
 explication_en:'Hacer = to do / to make. Hace su trabajo.'},

{id:'es-pi-07',category:'Présent',level:'builder',type:'lacune',
 question:'Yo ___ (querer) aprender español.',
 answer_text:'quiero',
 hint:'Querer est irrégulier e→ie.',
 explication_fr:'Querer : yo QUIERO (irrégulier e→ie).',
 explication_en:'Querer: yo QUIERO (irregular e→ie).'},

{id:'es-pi-08',category:'Présent',level:'challenger',type:'traduction',
 question:'Traduire : "Nous apprenons l\'espagnol tous les jours."',
 answer_text:'Aprendemos español todos los días.',
 hint:'Nosotros → -emos pour -ER.',
 explication_fr:'Aprender (-ER) : nosotros APRENDEMOS. Todos los días = tous les jours.',
 explication_en:'Aprender: nosotros aprendemos. Todos los días = cada día.'},

{id:'es-pi-09',category:'Présent',level:'starter',type:'qcm',
 question:'Quel verbe signifie "pouvoir" ?',
 options:['querer','deber','poder','saber'],
 answer_index:2,answer_text:'poder',
 hint:'¿Puedo ayudarte?',
 explication_fr:'Poder = pouvoir. Yo PUEDO (irrégulier o→ue).',
 explication_en:'Poder = to be able to. Yo puedo.'},

{id:'es-pi-10',category:'Présent',level:'builder',type:'qcm',
 question:'"Saber" vs "Conocer" : "je sais que…" utilise :',
 options:['Conozco que…','Sé que…','Tengo que…','Estoy que…'],
 answer_index:1,answer_text:'Sé que…',
 hint:'Saber = savoir (fait).',
 explication_fr:'Saber = savoir (fait, info). Conocer = connaître (personne, lieu).',
 explication_en:'Saber = saber un hecho. Conocer = conocer a alguien.'},

// ══ PASSÉ (pretérito indefinido) (10) ════════════════════════
{id:'es-pa-01',category:'Passé',level:'builder',type:'qcm',
 question:'Passé indéfini de "hablar" à "yo" :',
 options:['hablé','hablaba','he hablado','hablaste'],
 answer_index:0,answer_text:'hablé',
 hint:'Yo → -é pour -AR au passé simple.',
 explication_fr:'Pretérito indefinido -AR : yo HABLÉ, tú hablaste.',
 explication_en:'Pretérito indefinido: yo HABLÉ (verbos -AR).'},

{id:'es-pa-02',category:'Passé',level:'builder',type:'qcm',
 question:'"Ayer comí en el mercado" signifie :',
 options:["Aujourd'hui je mange au marché","Hier j'ai mangé au marché","Je mangerai au marché","Je mangeais au marché"],
 answer_index:1,answer_text:"Hier j'ai mangé au marché",
 hint:'Ayer = hier. Comí = j\'ai mangé.',
 explication_fr:'Ayer = hier. Comer → yo COMÍ (passé simple).',
 explication_en:'Ayer = yesterday. Comí = pretérito indefinido de comer.'},

{id:'es-pa-03',category:'Passé',level:'builder',type:'lacune',
 question:'Ella ___ (salir) tarde ayer.',
 answer_text:'salió',
 hint:'Él/Ella → -ió pour -IR/-ER.',
 explication_fr:'Pretérito indefinido -ER/-IR : él/ella SALIÓ.',
 explication_en:'Pretérito indefinido: él/ella SALIÓ (verbos -IR).'},

{id:'es-pa-04',category:'Passé',level:'builder',type:'qcm',
 question:'Passé indéfini de "ir" (aller) à "nosotros" :',
 options:['fuimos','íbamos','fuisteis','fueron'],
 answer_index:0,answer_text:'fuimos',
 hint:'Ir et ser ont le même passé : fu-.',
 explication_fr:'IR et SER ont le même passé ! Nosotros FUIMOS.',
 explication_en:'IR y SER tienen el mismo pretérito: nosotros FUIMOS.'},

{id:'es-pa-05',category:'Passé',level:'builder',type:'qcm',
 question:'"¿Qué hiciste ayer?" signifie :',
 options:["Qu'as-tu fait hier ?","Que fais-tu hier ?","Qu'avais-tu fait ?","Que feras-tu ?"],
 answer_index:0,answer_text:"Qu'as-tu fait hier ?",
 hint:'Hiciste = tu as fait (hacer irrégulier).',
 explication_fr:'Hacer irrégulier : yo HICE, tú HICISTE.',
 explication_en:'Hacer: yo hice, tú hiciste, él hizo.'},

{id:'es-pa-06',category:'Passé',level:'challenger',type:'traduction',
 question:'Traduire : "Diallo est arrivé en retard à la réunion."',
 answer_text:'Diallo llegó tarde a la reunión.',
 hint:'Llegar (-AR) → llegó.',
 explication_fr:'Llegar → él/ella LLEGÓ. Tarde = en retard.',
 explication_en:'Llegar → llegó. Tarde = late.'},

{id:'es-pa-07',category:'Passé',level:'builder',type:'qcm',
 question:'Verbe irrégulier au passé : "tener" à "yo" :',
 options:['tené','tuví','tuve','tenié'],
 answer_index:2,answer_text:'tuve',
 hint:'Tener : yo tuve.',
 explication_fr:'Tener irrégulier : yo TUVE, tú tuviste, él tuvo.',
 explication_en:'Tener irregular: yo TUVE, tú tuviste, él tuvo.'},

{id:'es-pa-08',category:'Passé',level:'challenger',type:'qcm',
 question:'Phrase correcte au passé :',
 options:['Ayer nosotros trabajamos mucho.','Ayer nosotros trabajemos mucho.','Ayer nosotros trabajábamos mucho.','Ayer nosotros trabajaron mucho.'],
 answer_index:0,answer_text:'Ayer nosotros trabajamos mucho.',
 hint:'Nosotros -AR = -amos (même forme présent et passé).',
 explication_fr:'Nosotros -AR : même forme pour présent et passé simple ! TRABAJAMOS.',
 explication_en:'Nosotros -AR: trabajamos = présent ET passé simple!'},

{id:'es-pa-09',category:'Passé',level:'builder',type:'lacune',
 question:'Yo ___ (ver) ese programa ayer.',
 answer_text:'vi',
 hint:'Ver irrégulier : vi.',
 explication_fr:'Ver (voir) irrégulier : yo VI, tú viste, él vio.',
 explication_en:'Ver: yo VI, tú viste, él vio.'},

{id:'es-pa-10',category:'Passé',level:'builder',type:'qcm',
 question:'"Vine, vi, vencí" — "vine" est le passé de :',
 options:['ir','ver','venir','vencer'],
 answer_index:2,answer_text:'venir',
 hint:'Venir irrégulier.',
 explication_fr:'Venir : yo VINE (irrégulier). = Je suis venu.',
 explication_en:'Venir: yo VINE (irregular). = I came.'},

// ══ FUTUR (8) ═════════════════════════════════════════════════
{id:'es-fu-01',category:'Futur',level:'builder',type:'qcm',
 question:'Futur simple de "hablar" à "yo" :',
 options:['hablaré','hablaría','hablo','hablaré'],
 answer_index:0,answer_text:'hablaré',
 hint:'Infinitif + -é.',
 explication_fr:'Futur simple = infinitif + terminaisons : -é, -ás, -á, -emos, -éis, -án.',
 explication_en:'Futuro simple: infinitivo + -é, -ás, -á, -emos, -éis, -án.'},

{id:'es-fu-02',category:'Futur',level:'builder',type:'qcm',
 question:'"Mañana iremos a la oficina" signifie :',
 options:["Hier nous sommes allés au bureau","Demain nous irons au bureau","Nous allons au bureau","Nous allions au bureau"],
 answer_index:1,answer_text:'Demain nous irons au bureau',
 hint:'Mañana = demain.',
 explication_fr:'Mañana = demain. Iremos = nous irons (futur de IR).',
 explication_en:'Mañana = tomorrow. Iremos = futuro de IR (irregular).'},

{id:'es-fu-03',category:'Futur',level:'builder',type:'lacune',
 question:'Ella ___ (venir) a la conferencia.',
 answer_text:'vendrá',
 hint:'Venir irrégulier au futur : vendr-.',
 explication_fr:'Venir irrégulier futur : vendr-. Ella VENDRÁ.',
 explication_en:'Venir futuro irregular: vendr-. Ella vendrá.'},

{id:'es-fu-04',category:'Futur',level:'builder',type:'qcm',
 question:'"Ir a + infinitif" sert à :',
 options:['parler du passé','exprimer le futur proche','demander la permission','exprimer le présent'],
 answer_index:1,answer_text:'exprimer le futur proche',
 hint:'Voy a estudiar = je vais étudier.',
 explication_fr:'Ir a + infinitif = futur proche. Voy a llamar = je vais appeler.',
 explication_en:'Ir a + infinitivo = futuro próximo. Voy a llamar.'},

{id:'es-fu-05',category:'Futur',level:'challenger',type:'traduction',
 question:'Traduire : "Est-ce que tu auras le rapport demain ?"',
 answer_text:'¿Tendrás el informe mañana?',
 hint:'Tener irrégulier futur : tendr-.',
 explication_fr:'Tener futur irrégulier : tendr-. ¿TENDRÁS?',
 explication_en:'Tener futuro: tendr-. ¿Tendrás el informe mañana?'},

{id:'es-fu-06',category:'Futur',level:'builder',type:'qcm',
 question:'Futur de "hacer" à "ellos" :',
 options:['harán','hacerán','hacarán','hazerán'],
 answer_index:0,answer_text:'harán',
 hint:'Hacer futur irrégulier : har-.',
 explication_fr:'Hacer futur irrégulier : har-. Ellos HARÁN.',
 explication_en:'Hacer futuro: har-. Ellos harán.'},

{id:'es-fu-07',category:'Futur',level:'challenger',type:'qcm',
 question:'"Cuando llegues, te llamaré" utilise le futur car :',
 options:["c'est une condition future","c'est une habitude","c'est le passé","c'est une obligation"],
 answer_index:0,answer_text:"c'est une condition future",
 hint:'Te llamaré = je t\'appellerai.',
 explication_fr:'QUAND + subjonctif en espagnol pour le futur. Te LLAMARÉ = je t\'appellerai.',
 explication_en:'Cuando + subjuntivo para futuro. Te llamaré = I will call you.'},

{id:'es-fu-08',category:'Futur',level:'builder',type:'qcm',
 question:'"Voy a enviar el correo" signifie :',
 options:["J'envoie le mail","J'ai envoyé le mail","Je vais envoyer le mail","J'enverrai le mail"],
 answer_index:2,answer_text:'Je vais envoyer le mail',
 hint:'Voy a + infinitif = futur proche.',
 explication_fr:'Voy a + infinitif = je vais + inf. Futur proche.',
 explication_en:'Voy a + infinitivo = near future. Voy a enviar.'},

// ══ VOCABULAIRE (8) ═══════════════════════════════════════════
{id:'es-vo-01',category:'Vocabulaire',level:'starter',type:'qcm',
 question:'"El trabajo" signifie :',
 options:['la réunion','le travail','le bureau','le rapport'],
 answer_index:1,answer_text:'le travail',
 hint:'Travailler = trabajar.',
 explication_fr:'Trabajo = le travail. Trabajar = travailler.',
 explication_en:'El trabajo = work. Trabajar = to work.'},

{id:'es-vo-02',category:'Vocabulaire',level:'starter',type:'qcm',
 question:'"Muchas gracias" signifie :',
 options:['Je vous en prie','Bonne chance','Merci beaucoup','Félicitations'],
 answer_index:2,answer_text:'Merci beaucoup',
 hint:'Gracias = merci.',
 explication_fr:'Muchas gracias = Merci beaucoup. Respuesta: De nada.',
 explication_en:'Muchas gracias = Thank you very much. Respuesta: De nada.'},

{id:'es-vo-03',category:'Vocabulaire',level:'builder',type:'qcm',
 question:'"Sin embargo" signifie :',
 options:['donc','car','cependant','ensuite'],
 answer_index:2,answer_text:'cependant',
 hint:'Connecteur d\'opposition.',
 explication_fr:'Sin embargo = cependant, néanmoins.',
 explication_en:'Sin embargo = however, nevertheless.'},

{id:'es-vo-04',category:'Vocabulaire',level:'builder',type:'qcm',
 question:'"La empresa" signifie :',
 options:["l'entreprise","l'employé","l'emploi","l'employeur"],
 answer_index:0,answer_text:"l'entreprise",
 hint:'Empresa ≠ empleado.',
 explication_fr:'Empresa = entreprise. Empleado = employé.',
 explication_en:'La empresa = the company. El empleado = the employee.'},

{id:'es-vo-05',category:'Vocabulaire',level:'builder',type:'qcm',
 question:'"Enseguida" signifie :',
 options:['tout à l\'heure','tout de suite','rarement','bientôt'],
 answer_index:1,answer_text:'tout de suite',
 hint:'Très courant au téléphone.',
 explication_fr:'Enseguida = tout de suite, immédiatement.',
 explication_en:'Enseguida = right away, immediately.'},

{id:'es-vo-06',category:'Vocabulaire',level:'challenger',type:'qcm',
 question:'"Aunque" signifie :',
 options:['ainsi que','bien que / même si','puisque','afin que'],
 answer_index:1,answer_text:'bien que / même si',
 hint:'Connecteur de concession.',
 explication_fr:'Aunque = bien que, même si, quoique.',
 explication_en:'Aunque = although, even if, even though.'},

{id:'es-vo-07',category:'Vocabulaire',level:'starter',type:'qcm',
 question:'"El correo electrónico" signifie :',
 options:["le téléphone","le réseau","l'e-mail","le document"],
 answer_index:2,answer_text:"l'e-mail",
 hint:'Correo = courrier.',
 explication_fr:'Correo electrónico = e-mail. Mandar un correo = envoyer un mail.',
 explication_en:'Correo electrónico = email. Mandar = send.'},

{id:'es-vo-08',category:'Vocabulaire',level:'builder',type:'qcm',
 question:'"Disponible" en espagnol signifie :',
 options:['occupé','absent','disponible','en réunion'],
 answer_index:2,answer_text:'disponible',
 hint:'Même mot qu\'en français !',
 explication_fr:'Disponible = disponible. Mot identique en espagnol et français.',
 explication_en:'Disponible = available. Palabra idéntica en francés y español.'},

// ══ NOMBRES ET TEMPS (6) ══════════════════════════════════════
{id:'es-nt-01',category:'Nombres',level:'starter',type:'qcm',
 question:'Comment dit-on "25" en espagnol ?',
 options:['veinticinco','veinte y cinco','vintcinco','vinticinco'],
 answer_index:0,answer_text:'veinticinco',
 hint:'20-29 s\'écrivent en un seul mot.',
 explication_fr:'De 21 à 29, les nombres s\'écrivent en un seul mot: veinticinco.',
 explication_en:'Del 21 al 29 se escriben juntos: veinticinco, veintidós, etc.'},

{id:'es-nt-02',category:'Nombres',level:'starter',type:'qcm',
 question:'"Son las tres y media" signifie :',
 options:['Il est 3h15','Il est 3h30','Il est 3h45','Il est 2h30'],
 answer_index:1,answer_text:'Il est 3h30',
 hint:'Media = demi.',
 explication_fr:'Y media = et demie. Son las tres y media = 3h30.',
 explication_en:'Y media = half past. Son las tres y media = 3:30.'},

{id:'es-nt-03',category:'Nombres',level:'builder',type:'qcm',
 question:'"¿A qué hora es la reunión?" — réponse correcte :',
 options:['Es a las 2.','Son a las 2.','Está a las 2.','Tiene a las 2.'],
 answer_index:0,answer_text:'Es a las 2.',
 hint:'Événement unique → ES (singulier).',
 explication_fr:'Heure d\'événement unique → ES. Es a las 2.',
 explication_en:'Evento único → ES (singular). La reunión es a las 2.'},

{id:'es-nt-04',category:'Nombres',level:'starter',type:'qcm',
 question:'Comment dit-on 100 en espagnol ?',
 options:['ciento','cien','cientos','cent'],
 answer_index:1,answer_text:'cien',
 hint:'100 seul = cien. 101+ = ciento.',
 explication_fr:'100 seul = CIEN. 101 = ciento uno. 200 = doscientos.',
 explication_en:'100 alone = CIEN. 101 = ciento uno.'},

{id:'es-nt-05',category:'Nombres',level:'builder',type:'qcm',
 question:'"El lunes" signifie :',
 options:['dimanche','samedi','lundi','vendredi'],
 answer_index:2,answer_text:'lundi',
 hint:'Lunes vient de Luna (Lune).',
 explication_fr:'Lunes = lundi. Martes = mardi. Miércoles = mercredi.',
 explication_en:'Lunes = Monday. Martes = Tuesday. Miércoles = Wednesday.'},

{id:'es-nt-06',category:'Nombres',level:'builder',type:'qcm',
 question:'Comment dit-on "le 15 janvier" ?',
 options:['el quince enero','el quince de enero','el quinceavo de enero','los quince de enero'],
 answer_index:1,answer_text:'el quince de enero',
 hint:'Article EL + nombre + DE + mois.',
 explication_fr:'Date : EL + nombre cardinal + DE + mois. El quince de enero.',
 explication_en:'Fecha: el + número cardinal + de + mes.'},

// ══ QUESTIONS (6) ═════════════════════════════════════════════
{id:'es-qu-01',category:'Questions',level:'starter',type:'qcm',
 question:'"¿Por qué?" signifie :',
 options:['Comment ?','Pourquoi ?','Combien ?','Lequel ?'],
 answer_index:1,answer_text:'Pourquoi ?',
 hint:'Pourquoi ↔ parce que.',
 explication_fr:'¿Por qué? = Pourquoi ? | Porque = parce que.',
 explication_en:'¿Por qué? = Why? | Porque = because.'},

{id:'es-qu-02',category:'Questions',level:'starter',type:'qcm',
 question:'"¿Cuánto cuesta?" signifie :',
 options:["C'est combien ?","Où est-ce ?","Quand ?","Comment ?"],
 answer_index:0,answer_text:"C'est combien ?",
 hint:'Cuánto = combien.',
 explication_fr:'¿Cuánto cuesta? = Combien ça coûte ? Très utile.',
 explication_en:'¿Cuánto cuesta? = How much does it cost?'},

{id:'es-qu-03',category:'Questions',level:'builder',type:'qcm',
 question:'"¿Cuál es su nombre?" signifie :',
 options:['Comment vous appelez-vous ?','Quel est votre nom ?','Où habitez-vous ?','Que faites-vous ?'],
 answer_index:1,answer_text:'Quel est votre nom ?',
 hint:'Cuál = lequel / quel.',
 explication_fr:'¿Cuál es…? = Quel est… ? ¿Cuál es su nombre? = Quel est votre nom?',
 explication_en:'¿Cuál es? = What is? ¿Cuál es su nombre? = What is your name?'},

{id:'es-qu-04',category:'Questions',level:'builder',type:'lacune',
 question:'¿___ vives tú?',
 answer_text:'Dónde',
 hint:'Dónde = où.',
 explication_fr:'¿Dónde vives? = Où habites-tu ?',
 explication_en:'¿Dónde vives? = Where do you live?'},

{id:'es-qu-05',category:'Questions',level:'builder',type:'qcm',
 question:'Traduction de "Depuis combien de temps ?" :',
 options:['¿Cuándo?','¿Desde cuándo?','¿Cuánto tiempo antes?','¿Hace cuánto?'],
 answer_index:3,answer_text:'¿Hace cuánto?',
 hint:'Hace + temps = il y a.',
 explication_fr:'¿Hace cuánto? ou ¿Desde cuándo? = Depuis combien de temps ?',
 explication_en:'¿Hace cuánto? = How long ago? ¿Desde cuándo? = Since when?'},

{id:'es-qu-06',category:'Questions',level:'challenger',type:'traduction',
 question:'Traduire : "Combien d\'employés y a-t-il dans cette entreprise ?"',
 answer_text:'¿Cuántos empleados hay en esta empresa?',
 hint:'Hay = il y a. Cuántos = combien de.',
 explication_fr:'¿Cuántos…hay en…? = Combien de… y a-t-il dans… ?',
 explication_en:'¿Cuántos…hay? = How many…are there?'},


// ══ VERBES RÉFLEXIFS (6) ══════════════════════════════════════
{id:'es-rf-01',category:'Réflexifs',level:'starter',type:'qcm',
 question:'Comment dit-on "je me lève" ?',
 options:['Levanto yo','Me levanto','Yo me levantó','Levantame'],
 answer_index:1,answer_text:'Me levanto',
 hint:'Réfléchi : me + verbe conjugué.',
 explication_fr:'Verbe réflexif : PRONOMBRE + verbe. Me levanto.',
 explication_en:'Verbo reflexivo: pronombre reflexivo + verbo. Me levanto.'},

{id:'es-rf-02',category:'Réflexifs',level:'starter',type:'qcm',
 question:'"Se llama Emma" signifie :',
 options:["Elle l'appelle Emma","Elle s'appelle Emma","Il appelle Emma","Emma appelle"],
 answer_index:1,answer_text:"Elle s'appelle Emma",
 hint:'Llamarse = s\'appeler.',
 explication_fr:'Llamarse = s\'appeler. Se llama = il/elle s\'appelle.',
 explication_en:'Llamarse = to be called. Se llama = he/she is called.'},

{id:'es-rf-03',category:'Réflexifs',level:'builder',type:'lacune',
 question:'¿A qué hora ___ tú? (acostarse = se coucher)',
 answer_text:'te acuestas',
 hint:'Tú + réflexif te + o→ue.',
 explication_fr:'Acostarse (o→ue) : yo me acuesto, tú TE ACUESTAS.',
 explication_en:'Acostarse (o→ue): yo me acuesto, tú te acuestas.'},

{id:'es-rf-04',category:'Réflexifs',level:'builder',type:'qcm',
 question:'"Nos vamos" signifie :',
 options:['Nous allons là-bas','Nous partons','Nous revenons','Nous restons'],
 answer_index:1,answer_text:'Nous partons',
 hint:'Irse = partir / s\'en aller.',
 explication_fr:'IRSE = partir. Nos vamos = nous partons.',
 explication_en:'Irse = to leave/go away. Nos vamos = we are leaving.'},

{id:'es-rf-05',category:'Réflexifs',level:'builder',type:'qcm',
 question:'Traduction de "se sentir fatigué" :',
 options:['sentarse cansado','sentirse cansado','sientarse cansado','se senta cansado'],
 answer_index:1,answer_text:'sentirse cansado',
 hint:'Sentirse = se sentir.',
 explication_fr:'Sentirse = se sentir. Sentarse = s\'asseoir. Attention à la distinction.',
 explication_en:'Sentirse = to feel. Sentarse = to sit down.'},

{id:'es-rf-06',category:'Réflexifs',level:'challenger',type:'traduction',
 question:'Traduire : "Ils se sont rencontrés au bureau hier."',
 answer_text:'Se conocieron en la oficina ayer.',
 hint:'Conocerse = se rencontrer / se connaître.',
 explication_fr:'Conocerse réflexif réciproque. Se conocieron = ils se sont rencontrés.',
 explication_en:'Conocerse = to meet each other. Se conocieron = they met.'},

// ══ ARTICLES ET GENRE (6) ════════════════════════════════════
{id:'es-ag-01',category:'Articles',level:'starter',type:'qcm',
 question:'Article défini correct pour "livre" (libro) :',
 options:['la libro','el libro','los libra','una libro'],
 answer_index:1,answer_text:'el libro',
 hint:'Libro est masculin.',
 explication_fr:'LIBRO = masculin → EL libro. Article défini masc. sing. = EL.',
 explication_en:'Libro = masculine → EL libro. Definite article masc. sing. = EL.'},

{id:'es-ag-02',category:'Articles',level:'starter',type:'qcm',
 question:'"La empresa" utilise l\'article féminin car :',
 options:['tous les mots en -a sont féminins','empresa est féminin','empresa finit en -a','les deux premières raisons'],
 answer_index:2,answer_text:'empresa finit en -a',
 hint:'La plupart des mots en -a sont féminins.',
 explication_fr:'En espagnol, les mots en -A sont généralement féminins → LA empresa.',
 explication_en:'Words ending in -A are generally feminine → LA empresa.'},

{id:'es-ag-03',category:'Articles',level:'builder',type:'qcm',
 question:'Pluriel de "el problema" :',
 options:['las problemas','los problemas','el problemas','los problemás'],
 answer_index:1,answer_text:'los problemas',
 hint:'Problema est masculin malgré le -a.',
 explication_fr:'PROBLEMA est masculin (exception). Pluriel : LOS problemas.',
 explication_en:'Problema is masculine (exception to -a rule). LOS problemas.'},

{id:'es-ag-04',category:'Articles',level:'builder',type:'qcm',
 question:'Article indéfini pour "une réunion" :',
 options:['un reunión','una reunión','unos reunión','la reunión'],
 answer_index:1,answer_text:'una reunión',
 hint:'Reunión = féminin.',
 explication_fr:'Reunión = féminin → UNA reunión. Un = masc. / Una = fém.',
 explication_en:'Reunión = feminine → UNA reunión.'},

{id:'es-ag-05',category:'Articles',level:'builder',type:'qcm',
 question:'"No tengo ___ coche." (sans article = pas de voiture)',
 options:['un','el','ningún','—'],
 answer_index:3,answer_text:'—',
 hint:'Négation + pas de déterminant nécessaire.',
 explication_fr:'Après négation, on peut omettre l\'article : No tengo coche.',
 explication_en:'After negation, article is often omitted: No tengo coche.'},

{id:'es-ag-06',category:'Articles',level:'challenger',type:'traduction',
 question:'Traduire : "Les étudiants ont besoin d\'un bon professeur."',
 answer_text:'Los estudiantes necesitan un buen profesor.',
 hint:'Buen (masc. devant nom) = bueno raccourci.',
 explication_fr:'BUENO → BUEN devant un nom masculin. Los estudiantes (pluriel masc.).',
 explication_en:'Bueno → buen before masculine noun. Los estudiantes.'},

// ══ DEBER / HAY QUE / TENER QUE (4) ══════════════════════════
{id:'es-ob-01',category:'Obligation',level:'builder',type:'qcm',
 question:'"Hay que estudiar" signifie :',
 options:["Il faut étudier","J'étudie","Il y a des études","Il faudrait étudier"],
 answer_index:0,answer_text:'Il faut étudier',
 hint:'Hay que = il faut (impersonnel).',
 explication_fr:'HAY QUE + infinitif = il faut (valeur générale, impersonnelle).',
 explication_en:'Hay que + infinitivo = it is necessary to (impersonal).'},

{id:'es-ob-02',category:'Obligation',level:'builder',type:'qcm',
 question:'"Debes llamar al médico" signifie :',
 options:['Tu peux appeler le médecin','Tu dois appeler le médecin','Il faut appeler le médecin','Tu as appelé le médecin'],
 answer_index:1,answer_text:'Tu dois appeler le médecin',
 hint:'Deber = devoir.',
 explication_fr:'DEBER + infinitif = devoir (obligation personnelle).',
 explication_en:'Deber + infinitivo = must/should (personal obligation).'},

{id:'es-ob-03',category:'Obligation',level:'builder',type:'lacune',
 question:'Nosotros ___ terminar el proyecto hoy. (tener que)',
 answer_text:'tenemos que',
 hint:'Nosotros + tener que.',
 explication_fr:'TENER QUE + infinitif = avoir à, devoir. Nosotros TENEMOS QUE.',
 explication_en:'Tener que + infinitivo = to have to. Nosotros tenemos que.'},

{id:'es-ob-04',category:'Obligation',level:'challenger',type:'traduction',
 question:'Traduire : "Il ne faut pas oublier les documents."',
 answer_text:'No hay que olvidar los documentos.',
 hint:'No hay que = il ne faut pas.',
 explication_fr:'NO HAY QUE = il ne faut pas (interdiction douce).',
 explication_en:'No hay que = one must not (general prohibition).'},

// ══ VOCABULAIRE BUSINESS (4) ══════════════════════════════════
{id:'es-biz-01',category:'Vocabulaire',level:'builder',type:'qcm',
 question:'"El plazo" dans un contexte professionnel signifie :',
 options:['le plateau','la place','le délai / la deadline','le plan'],
 answer_index:2,answer_text:'le délai / la deadline',
 hint:'Entregar antes del plazo = livrer avant la deadline.',
 explication_fr:'El plazo = le délai, la date limite. Très courant en entreprise.',
 explication_en:'El plazo = deadline, time limit.'},

{id:'es-biz-02',category:'Vocabulaire',level:'builder',type:'qcm',
 question:'"Solicitar" signifie :',
 options:['solliciter / demander','soulever','souhaiter','solidariser'],
 answer_index:0,answer_text:'solliciter / demander',
 hint:'Cognate : solicitar ≈ solliciter.',
 explication_fr:'Solicitar = demander officiellement, solliciter.',
 explication_en:'Solicitar = to request, to apply for.'},

{id:'es-biz-03',category:'Vocabulaire',level:'challenger',type:'qcm',
 question:'"El presupuesto" signifie :',
 options:['le prix','le budget / le devis','le bénéfice','le prêt'],
 answer_index:1,answer_text:'le budget / le devis',
 hint:'Hacer un presupuesto = faire un devis.',
 explication_fr:'El presupuesto = le budget ou le devis (selon contexte).',
 explication_en:'El presupuesto = budget or estimate/quote.'},

{id:'es-biz-04',category:'Vocabulaire',level:'builder',type:'qcm',
 question:'"En cuanto antes" signifie :',
 options:['dans longtemps','le plus tôt possible','en avance','dès maintenant'],
 answer_index:1,answer_text:'le plus tôt possible',
 hint:'Cuanto antes = dès que possible.',
 explication_fr:'Cuanto antes = le plus tôt possible. Très courant dans les emails pro.',
 explication_en:'Cuanto antes = as soon as possible (ASAP).'},
];

// ─── FONCTIONS D'ACCÈS ESPAGNOL ───────────────────────────────

/** Retourne toutes les catégories du pool espagnol. */
function getAllCategoriesES() {
  return [...new Set(QUESTION_POOL_ES.map(q => q.category))];
}

/** Taille du pool espagnol pour une catégorie. */
function getPoolSizeForCategoryES(category) {
  return QUESTION_POOL_ES.filter(q => q.category === category).length;
}

/** Questions espagnol filtrées par catégorie + niveau. */
function getQuestionsForCategoryES(category, level) {
  const order = { starter: 0, builder: 1, challenger: 2 };
  const maxLevel = order[level] ?? 1;
  return QUESTION_POOL_ES.filter(q =>
    q.category === category &&
    (order[q.level] ?? 0) <= maxLevel
  );
}

/** Sélectionne une question espagnol non posée. */
function pickQuestionES(category, level, askedIds = []) {
  const candidates = getQuestionsForCategoryES(category, level)
    .filter(q => !askedIds.includes(q.id));
  if (candidates.length === 0) return null;
  return candidates[Math.floor(Math.random() * candidates.length)];
}
